#+OPTIONS: ^:{}

Stuff for the Sac and Jane paper on turbulence diagnostics

* Answering the referee report
:PROPERTIES:
:noweb:    yes
:END:
Points for Will to look at: 8, 11, 12

** Make text doc with Will's replies to referee
#+BEGIN_SRC org :tangle will-replies.org :noweb yes
<<will-replies>>
#+END_SRC
** Make LaTeX doc with Will's changes to text

*** LaTeX wrapper for new bits
#+BEGIN_SRC latex :tangle will-ms-changes.tex :noweb yes
\documentclass[useAMS,usenatbib]{mn2e}
\pdfminorversion=4
\usepackage{bm}
\usepackage{graphicx}

%\renewcommand\includegraphics[2][]{}
\nonstopmode

\newcounter{ionstage}
\newcommand{\ion}[2]{\setcounter{ionstage}{#2}% 
  \ensuremath{\mathrm{#1\,\scriptstyle\Roman{ionstage}}}}
\newcommand\nii{[\ion{N}{2}]}
\newcommand\sii{[\ion{S}{2}]}
\newcommand\oiii{[\ion{O}{3}]}
\newcommand\ha{\ensuremath{\mathrm{H\alpha}}}
\newcommand\hii{\ion{H}{2}}

%% New macros that are needed for version 2 of the MS
<<will-new-macros>>

\begin{document}

\setcounter{section}{2}\setcounter{subsection}{3}\setcounter{subsubsection}{2}
\subsubsection{Velocity channel analysis}
\label{sec:stats-vca} %% New label for sec 2.3.3
<<text-for-233>>

\setcounter{figure}{5}
\setcounter{section}{3}\setcounter{subsection}{2}\setcounter{subsubsection}{1}
\subsubsection{Second-order Structure Functions}
\label{sssec:s2func}
<<text-for-322>>

\subsubsection{Velocity Channel Analysis}
\label{sssec:vca}
<<text-for-323>>

\setcounter{section}{4}\setcounter{subsection}{1}\setcounter{subsubsection}{1}
\subsubsection{Structure Function}
\label{sssec:strfunc}
<<text-for-412>>

\setcounter{section}{4}\setcounter{subsection}{1}\setcounter{subsubsection}{2}
<<text-for-413>>

\appendix
\section[]{Example second-order structure functions of the line-of-sight velocity centroids}
\label{app:sf}
<<text-for-A>>
\section[]{Example power spectra from Velocity Channel Analysis}
\label{app:vca}
<<text-for-B>>
\end{document}
#+END_SRC


*** Compile the doc
This setting is needed so that TABs don't get stripped
#+BEGIN_SRC elisp :results silent
(setq org-src-preserve-indentation t)
#+END_SRC

#+BEGIN_SRC makefile :tangle will-ms.mk
MS=will-ms-changes

open-pdf: $(MS).pdf
	open $(MS).pdf

$(MS).pdf: $(MS).tex
	pdflatex $< ; pdflatex $< ; open $@

#+END_SRC

#+BEGIN_SRC sh :results silent
make -f will-ms.mk
#+END_SRC


** Point 8
#+BEGIN_SRC org :noweb-ref will-replies
: 8. The crucial section 3.2.3 on the superiority of the VCA needs work.  It refers to data not presented on the intermediate velocity slices; it uses a pagelong table rather than a figure to present the information needed (as I noted above); and as a result doesn't clearly make the correct that thermal broadening destroys the value of the thin slices. (Is this indeed still true for the heavier, narrower, ions?)

#+END_SRC

*** Changes:
#+BEGIN_SRC org :noweb-ref will-replies
We have followed the referee's suggestion and replaced the table with a new figure that shows the time evolution of the VCA power law indices.  The detailed graphs of the VCAs have been moved to an appendix.  Also, we have rewritten the text to make clearer that it is only for H alpha that thermal broadening destroys the value of the thin slices. 
#+END_SRC

#+BEGIN_SRC latex :noweb-ref will-new-macros
\newcommand\gammaVCAthin{\ensuremath{\gamma_{\mathrm{t}}}}
\newcommand\gammaVCAvthick{\ensuremath{\gamma_{\mathrm{T}}}}
\newcommand\mSF{\ensuremath{m_{\mathrm{2D}}}}
\newcommand\mSFddd{\ensuremath{m_{\mathrm{3D}}}}
#+END_SRC

**** Text for Appendix B
#+name: text-for-B
#+BEGIN_SRC latex
Figures~\ref{fig:vca} to~\ref{fig:vcayz} show the power spectra
resulting from the velocity channel analysis (see
\S~\ref{sec:stats-vca}). Each of the three figures is for a different
viewing direction and shows the four emission lines at four different
times. For each combination of line and time, there are two panels: an
upper panel without including thermal Doppler broadening and a lower
panel with the broadening effects included.  In each graph, two power
spectra are plotted: one representing a very thick velocity slice
(i.e., encompassing all the emission) and the other averaged over thin
velocity slices of width $\delta v \sim 5$~km~s$^{-1}$.  Also shown
are the least-squares power-law fits to the thin and very thick slice
spectra and the range in wavenumber over which the fit is
calculated. This wavenumber range corresponds to the length-scale
range used for the structure function fits (see
\S~\ref{sssec:s2func}).  The very thick velocity slice is equivalent
to the total intensity along the line of sight and its power spectrum
does not vary with the addition of thermal broadening.

It is clear that the thermal broadening has a large effect on the VCA
of the H$\alpha$ line, effectively erasing the difference in slope
between the thin and thick slices.  For photoionized gas at $T_e=
10^4$~K, the FWHM of the H$\alpha$ line is $\sim 22$~km~s$^{-1}$,
while that of an oxygen line is a quarter of this, $\sim
5.5$~km~s$^{-1}$.  Indeed, the heavier ions are less affected by thermal broadening, but a slight steepening of the thin-slice power spectra can still be seen, amounting to a reduction in \gammaVCAthin{} of \(\sim 0.1\). 

For the thermally broadened case, the variation with time of the
slopes of these fits, \gammaVCAvthick{} for the thick slices and
\gammaVCAthin{} for the thin slices, is shown in
Fig~\ref{fig:vcatrends} and discussed in \S~\ref{sssec:vca}.

#+END_SRC

**** Text for VCA results - sec 3.2.3

#+name: text-for-323
#+BEGIN_SRC latex
\begin{figure*}
%% Figure 8 in ms-resubmit.pdf
\centering
\includegraphics[width=\textwidth]{vca-time-trends-all}
\caption{ Evolution of velocity channel power-law index as a function
  of time for thick channels (\gammaVCAvthick; crosses) and thin
  channels (\gammaVCAthin; filled circles).  From top to bottom:
  H$\alpha$, \oiii{} $\lambda 5007$, \nii{} $\lambda 6584$, \sii{}
  $\lambda 6716$. From left to right: line of sight along the $z$, $x$
  and $y$ axes, respectively.  Thermal broadening was included in all
  cases.  }
\label{fig:vcatrends}
\end{figure*}

Figure~\ref{fig:vcatrends} shows the evolution with time of the VCA
slope from thin and thick channels (shown by filled circle and cross
symbols, respectively) for different ions and for different viewing
directions.  The individual VCA power spectra from which these slopes
were extracted are presented in Appendix~\ref{app:vca}.  It can be
seen that both \gammaVCAthin{} and \gammaVCAvthick{} are remarkably
stable with time during the latter part of the evolution (\(t >
200,000\)~years).  Although thermal broadening means that there is no
clear distinction between \gammaVCAthin{} and \gammaVCAvthick{} for
the H\(\alpha\) line, the two values are clearly distinguished for the
heavier ions, with the thin slices showing a significantly shallower
slope, especially for \oiii{}.  The implications for diagnosing
turbulence statistics are discussed in \S~\ref{sssec:vca2}.

#+END_SRC


**** Parallel changes for the SF section
#+BEGIN_SRC org :noweb-ref will-replies
We have made parallel changes to the previous section on the velocity centroid structure functions, moving the numerous graphs of the actual structure functions to an appendix and replacing the table with a graph that shows how the power law indices evolve with time.
#+END_SRC

***** Text for Appendix A
#+name: text-for-A
#+BEGIN_SRC latex
Figures~\ref{fig:sfunc} to \ref{fig:sfuncyz} show the second-order
structure functions of the line-of-sight velocity centroid maps (see
\S\S~\ref{sssec:strfunc} and \ref{subsubsec:centroid}) for the four
emission lines at the four evolutionary times depicted in
Figure~\ref{fig:HIIimages}.  If turbulence is present, the
second-order structure function should exhibit an inertial range over
which it is a power law with length scale. Accordingly, we perform a
least-squares fit to the data points. However, it is not immediately
clear what the limits for the fit should be. At small scales, the
lower limit for the inertial range should be defined by the scale at
which numerical dissipation effects cease to be important \citep
{2004ApJ...604..196B}. For the present simulations, we tested several
values and the size scale equivalent to 8 computational cells proved
to be adequate for all emission lines and evolution times studied. For
the upper limit, we examined the projected emission maps and
calculated the area occupied by the pixels having greater than 6.6\%
of the peak intensity. We then took the radius of the circle having
the same area to be the upper limit for the least-squares fit. This
procedure appears to work very well, as can be seen in
Figures~\ref{fig:sfunc} and \ref{fig:sfuncyz}. If a different line of
sight is chosen, the radius of this circle will be different and needs
to be calculated self-consistently for every projection.  Note that
the inertial range for each combination of line and view tends to
become broader with time due to the expansion of the \hii{} region.
At the latest time, 300,000~yrs, both the H$\alpha$ and \oiii$\lambda
5007$ structure functions appear to develop a break, which would be
better fit by two power laws, one below a scale of about 0.3~pc and a
steeper one for larger scales. However, we have fit just a single
power law to both of these cases.


An alternative criterion for the upper limit was used by \citet
{2011MNRAS.413..721L} who used the theoretical result for homogeneous
turbulence that decorrelation of the second-order structure function
occurs when the auto-correlation function changes sign from positive to
negative. This corresponds approximately to the scale for which the
second-order structure function is equal to 2. However, as can be seen
from Figures~\ref{fig:sfunc} and \ref{fig:sfuncyz}, 
for many of our emission lines this criterion cannot be used,
since the structure function nowhere rises above 2.

\begin{figure*}
  \centering
  \includegraphics[width=\textwidth]{sf-all-xy-ref}
  \caption{Second-order structure functions against length scale for
    projection onto the $xy$-plane. From top to bottom: H$\alpha$,
    \oiii$\lambda 5007$, \nii$\lambda 6584$, \sii$\lambda 6716$. From
    left to right: 150,000, 200,000, 250,000 and 300,000~years. The
    points represent the calculated structure function for the
    numerical simulation. The solid line is the least-squares fit to
    the data points between limits described in the text, represented
    by the grey rectangle. The horizontal dotted line at $\log 2$ is
    included as a reference value.}
\label{fig:sfunc}
\end{figure*}
\begin{figure*}
 \centering
 \includegraphics[width=\textwidth]{sf-all-xz-ref}
 \caption{Same as Fig.~\protect\ref{fig:sfunc} but for a projection
   onto the $xz$ plane.}
 \label{fig:sfuncxz}
\end{figure*}
\begin{figure*}
  \centering
  \includegraphics[width=\textwidth]{sf-all-yz-ref}
  \caption{Same as Fig.~\protect\ref{fig:sfunc} but for a projection
    onto the $yz$-plane.}
  \label{fig:sfuncyz}
\end{figure*}

#+END_SRC

***** Text for structure function results - sec 3.2.2
#+name: text-for-322
#+BEGIN_SRC latex 
\begin{figure*}
  \centering
  \includegraphics[width=\textwidth]{sf-time-trends-all}
  \caption{Evolution of second-order structure function power-law
    index, \mSF, as a function of time. From top to bottom: H$\alpha$,
    \oiii{} $\lambda 5007$, \nii{} $\lambda 6584$, \sii{} $\lambda
    6716$. From left to right: line of sight along the $z$, $x$ and
    $y$ axes, respectively.}
  \label{fig:sftrends}
\end{figure*}

\begin{figure*}
\centering
\includegraphics[width=0.6\linewidth]{pdf-centroid}
\caption{Histograms of velocity centroid values for each emission line
  along different lines of sight. From top to bottom: H$\alpha$,
  \oiii$\lambda 5007$, \nii$\lambda 6584$, \sii$\lambda 6716$. From
  left to right: line of sight along the $z$, $x$ and $y$ axes,
  respectively. The different line types refer to different times:
  thick, grey line---150,000~yrs, dashed line---200,000~yrs,
  short-dashed line---250,000~yrs, continuous black
  line---300,000~yrs.}
\label{fig:histogram}
\end{figure*}

We use the procedure described in Section~\ref{subsubsec:centroid} to
calculate velocity centroid maps for the H$\alpha$, \oiii$\lambda
5007$, \nii$\lambda 6584$ and also \sii$\lambda 6716$ emission lines
and then calculate the corresponding second-order structure functions
according to Equation~\ref{eq:strucfunc}. Results for representative
evolutionary times are shown in Figures~\ref{fig:sfunc} to
\ref{fig:sfuncyz} of Appendix~\ref{app:sf}, where power law fits to
the slope (\mSF) of the structure function are carried out for the
inertial range of scales.

In Figure~\ref{fig:sftrends} we show the evolution of \mSF{} with time
for the different lines and for the three principal viewing directions
of the simulation cube.  For the line of sight along the $z$-axis
(first column of Fig.~\ref{fig:sftrends}), one sees for all lines a
consistent steepening of the structure function graph with time
(increase in \mSF{}).  But for other viewing directions no such trend
is apparent: both rising and falling behavior of \mSF{} is seen, with
little consistency between different lines.

In order to understand why one particular viewing direction is
different, we produced histograms of the emission-line velocity
centroid values binned into narrow $<2$~km~s$^{-1}$ bins for the three
different lines of sight at the four different times. The histograms
are presented in Figure~\ref{fig:histogram}, from which we see that
for the $z$-axis line of sight, the values of $V_c$ are not
distributed symmetrically about the mean value and, in fact, for the
H$\alpha$ and \oiii$\lambda$5007 emission lines, a ``wing'' develops
for negative values of $V_c$ that extends to more negative values as
time progresses. This tendency is not seen for the $y$- and $x$- axis
lines of sight. We attribute this wing to a ``champagne'' flow towards
the observer along the $z$-axis. This flow would be perpendicular to
the line of sight for observations along the other axes.



%% WJH 25 Jul 2014 - Table of struc func indices removed

#+END_SRC


** Point 11
#+BEGIN_QUOTE
11. In section 4.1.2, what is the implication of ruling out the Kolmogorov value of the turbulence power law?  That is dropped into the discussion without a conclusion being drawn.
#+END_QUOTE


*** New tables of structure function slopes
+ These have changed slightly since the previous draft
+ We only use times after 200,00 years
| Time        | 200,000 |      |      | 250,000 |      |      | 300,000 |      |      |               |
| Plane       |     x−y |  x−z |  y−z |     x−y |  x−z |  y−z |     x−y |  x−z |  y−z | AVERAGE       |
|-------------+---------+------+------+---------+------+------+---------+------+------+---------------|
| Hα          |    0.61 | 0.49 | 0.55 |    0.71 | 0.49 | 0.47 |    0.82 | 0.53 | 0.62 | 0.59 +/- 0.04 |
| [OIII]λ5007 |    0.68 | 0.77 | 0.70 |    0.83 | 0.71 | 0.57 |    1.02 | 0.61 | 0.73 | 0.74 +/- 0.04 |
| [NII]λ6584  |    0.53 | 0.38 | 0.45 |    0.61 | 0.43 | 0.41 |    0.65 | 0.53 | 0.44 | 0.49 +/- 0.03 |
| [SII]λ6716  |    0.39 | 0.28 | 0.32 |    0.39 | 0.28 | 0.26 |    0.40 | 0.41 | 0.26 | 0.33 +/- 0.02 |
#+TBLFM: $11=vmeane($2..$10); f2

*** Changes

#+BEGIN_SRC org :noweb-ref will-replies
With respect to the particular question of the deviations from a
Kolmogorov spectrum, we feel that this is already addressed in the
previous section 4.1.1, where the second paragraph discusses precisely
this point.

We have, however made some additions to this section, including a new
figure that shows the (lack of) correlation between the structure
function slope and the underlying velocity fluctuations.  The exact
values of the slopes have also changed slightly due to adjustments we
have made to the power law fitting ranges, but this does not change
the qualitative conclusions.
#+END_SRC

#+name: text-for-412
#+BEGIN_SRC latex
The structure function of the velocity centroids is an observationally
attractive diagnostic because it is relatively immune to the effects
of thermal broadening and poor spectral resolution, so long as
sufficiently high signal-to-noise spectra are used.  However, it has
the disadvantage that relating the observed slope to the 3-dimensional
velocity statistics depends on the geometry of the emitting region,
see \S~\ref{subsec:projsmooth}.  For transverse separations larger
than the characteristic line-of-sight depth of the emitting gas, the
two-dimensional gradient should be equal to the three-dimensional one:
\[
m_{\mathrm{2D}} = m_{\mathrm{3D}} = -3 - n,
\]
whereas at smaller separations than this, projection smoothing, as
described above, means that the two-dimensional gradient is steeper:
\[
m_{\mathrm{2D}} = 1 + m_{\mathrm{3D}} = -2 - n.
\]
Based on our simulation's velocity power spectrum index at late times
of \(n \approx -3.2\) (see Figs.~\ref{fig:ps} and \ref{fig:psevol}),
the structure function slope should be \(m_{\mathrm{2D}} = 0.2\) in
the large-scale limit and \(m_{\mathrm{2D}} = 1.2\) in the small-scale
limit.

In fact, all of the measured slopes lie between these two limits,
with a systematically increasing value from low to high-ionization lines:
\(m_{\mathrm{2D}}(\sii) = 0.33 \pm 0.02\), 
\(m_{\mathrm{2D}}(\nii) = 0.49 \pm 0.03\), 
\(m_{\mathrm{2D}}(\ha) = 0.59 \pm 0.04\), 
\(m_{\mathrm{2D}}(\oiii) = 0.74 \pm 0.04\), where the averages were
performed for \(t > 200,000\)~years. 
This is qualitatively consistent with expectations because the
emission from lower-ionization lines is confined to thin layers near
the ionization front, whereas higher ionization emission is more
distributed over the volume and therefore subject to greater
projection smoothing.

If the line-of-sight depth were constant over the face of the \hii{}
region, then the structure function would show a break at a scale
equal to that depth, but in reality the depth varies from point to
point, so there will not be a sharp break.  Instead, the structure
function is expected to show negative curvature, with the gradient
gradually decreasing as one passes from smaller to larger scales.  A
small such effect is seen in the structure functions derived from our
simulations (Fig.~\ref{fig:sfunc} to \ref{fig:sfuncyz}): the fit to a
power law is generally not so good as in the case of the power
spectra, with negative residuals at both ends of the fitted range,
indicative of a negative curvature.  That the observed effect is so
small is probably due to the fact that the distribution of
line-of-sight depths strongly overlaps with the limited dynamic range
in separations available from our simulations, bounded at small scales
by numerical dissipation, and at large scales by the size of the
ionized region.

It is disappointing that none of the measured slopes reach either of
the limiting cases discussed above.  All that can be deduced from the
structure function is that \(1 + m_{\mathrm{3D}} >
m_{\mathrm{2D}}(\oiii)\) and \(m_{\mathrm{3D}} <
m_{\mathrm{2D}}(\sii)\), which implies $n = -2.74$ to $-3.33$.
Although this is a rather wide range of allowed velocity power
spectrum slopes, it does serve to clearly rule out the Kolmogorov value of \(n
= -3.667\).   Furthermore, the ``true'' value of \(n = -3.12 \pm 0.03
\) lies close to the middle of the allowed range.  

A further proviso to the use of the structure function is that
systematic anisotropic flows can affect the measured slopes when the
viewing angle is along the direction of the flow.  Such an effect is
seen at later times for our simulation when viewed along the
\(z\)-axis (Fig.~\ref{fig:sfunc}).  In this case, the structure
function tends to steepen at the large-scale end of our fitting range,
producing a positive curvature, which is opposite to the more typical
case of negative curvature discussed above.  Such cases may also be
identified by the presence of a significant skew in the PDF of the
line-of-sight velocity (see Fig.~\ref{fig:histogram}).

Figure~\ref{fig:sf-vs-n} illustrates these points by graphing the
correlation between the structure function slope \mSF{} and the slope
\(n\) of the underlying 3D velocity fluctuations.  The theoretical
relation is shown by black diagonal lines, both with (continuous line) and
without (dashed line) projection smoothing.  It is apparent that a
large part of the variation in \mSF{} is not driven by changes in
\(n\).  Indeed, \mSF{} shows a larger or equal variation in the latter
stages of evolution, when \(n\) is approximately constant, than it
does in the earlier stages, when \(n\) is varying.

\begin{figure}
  \centering
  \includegraphics[width=\linewidth]{sf-vs-3d-panels}
  \caption{Structure function slope versus velocity power law slope.  Each panel shows a different emission line; clockwise from upper left: \oiii{}, \ha{}, \sii{}, \nii{}.  Structure function slopes are shown for the 3 prinicipal viewing directions, distinguished by different symbol types (see key).  Dim gray lines and symbols show evolutionary times \(< 200,000\)~years, while black lines and symbols show times \(> 200,000\) years.} 
  \label{fig:sf-vs-n}
\end{figure}

Note that the additional complication identified by \citet
{2004ApJ...604..196B}, whereby correlations between density and
velocity fluctuations affect the translation between
\(m_{\mathrm{2D}}\) and \(n\), is likely of minor importance in our
case.  \citet {2007MNRAS.381.1733E} show that this is most important
for high Mach number turbulence, where \(\delta\rho/\langle \rho
\rangle > 1\), whereas the transonic turbulence inside our simulated
\hii{} regions produces more modest density contrasts.
\begin{figure*}
  \centering
  \includegraphics[width=\linewidth]{o3-thick-thin}
  \caption{Surface brightness maps in thick (left) versus thin (right)
    velocity slices for the \oiii{} line from our simulation at an age
    of 300,000~years.  The thick slice covers the full velocity range
    of the emission line, while the thin slice has a width of
    5~km~s$^{-1}$, which is smaller than the turbulent velocity
    fluctuations, but slightly larger than the thermal broadening for
    this line.  It is apparent that the thin slice shows considerably
    greater small-scale structure than the thick slice, which is
    reflected in its shallower power spectrum.  The brightness
    structure in the thick slice is due entirely to the emissivity
    fluctuations within the \hii{} region, whereas the additional
    structure in the thin slice is caused by velocity fluctuations.  }
  \label{fig:o3-thick-thin}
\end{figure*}

#+END_SRC
** Point 12
#+BEGIN_QUOTE
12. The crucial section 4.1.3 is where the VCA is demonstrated to work better than other methods. However, it is curiously anecdotal.  Given that the abstract and conclusion present this as the central point of the paper, use should be made of the vast amount of data presented for the VCA in Figure 9 and Table 3, to make a much more systematic comparison with the actual power spectra known from the 3D model.
#+END_QUOTE
*** Changes
#+name: text-for-413
#+BEGIN_SRC latex
\subsubsection{Velocity Channel Analysis}
\label{sssec:vca2}
The velocity channel analysis consists of calculating the
two-dimensional power spectrum of the brightness distribution
in isovelocity channels of varying thickness.  
We consider two cases: thick slices,
which are wide enough (\(\sim 100~\mathrm{km\ s^{-1}}\))
to include all the emission in the line,
and thin slices, with width \(5~\mathrm{km\ s^{-1}}\). 
Because the velocity spectrum in our simulations is rather shallow (see above),
the line-of-sight turbulent velocity dispersion \(\delta v\)
exceeds the width of these thin slices
over the full range of length scales that we can usefully study,
from \(0.1\)~pc (\(\delta v \approx 8~\mathrm{km\ s^{-1}}\))
to \(1\)~pc (\(\delta v \approx 10~\mathrm{km\
  s^{-1}}\)). Figure~\ref{fig:o3-thick-thin} shows typical examples of
the \oiii{} brightness in thick and thin slices.

To use thinner slices would not be useful for a variety of reasons.
First, \(5~\mathrm{km\ s^{-1}}\) corresponds to the highest resolution 
that can be achieved with optical spectrographs
that are optimised for studying extended sources,
such as Keck HIRES or VLT UVES. 
Second, thinner slices are increasingly subject to ``shot noise'' 
due to the finite resolution of the numerical simulations,
which produces spurious small-scale power, as discussed by 
\citet {2003MNRAS.342..325E} and \citet {2003ApJ...593..831M}.
Third, thermal broadening would smoothe out any structure on 
scales \(< 5~\mathrm{km\ s^{-1}}\) for all but the heaviest ions.

The procedure for deriving the power-law index
of the velocity fluctuations from the velocity channels is
slightly different, depending on whether the power spectrum 
of the emissivity fluctuations is ``steep'' or ``shallow'' (see above). 
In the steep case, which applies to \oiii{} in our simulation, 
the slope of the average power spectrum of the brightness maps
in the thin isovelocity channels is given by 
\(\gamma_{\mathrm{thin}} = -3 + \frac12 m_{\mathrm{3D}}\),
where \(m_{\mathrm{3D}} = -3 - n = 0.2 \pm 0.1\) for our simulation.
The derived value from the \oiii{} thin channel maps is 
\(\gamma_{\mathrm{thin}} = -2.84 \pm 0.11 \),
which compares very well with the value \(-2.9 \pm 0.05\)
that is implied by the simulation's value of \(n\). 

In the shallow case, it is the difference in slope
between the thin and thick slices
that is predicted to depend on the velocity fluctuations:
\(\gamma_{\mathrm{thin}} - \gamma_{\mathrm{vthick}} = \frac12 m_{\mathrm{3D}}\). 
The derived values are 
\(\gamma_{\mathrm{thin}} - \gamma_{\mathrm{vthick}} = 0.08 \pm 0.04\), 
\(0.18 \pm 0.04\), and \(0.18 \pm 0.04\)
for \ha, \nii, and \sii, respectively. 
These also compare well with the value of \(0.1 \pm 0.05\)
that is implied by the simulation's value of \(n\). 

The slopes of the power spectra of the thick slices themselves, 
which are simply the velocity-integrated surface brightness images\footnote{
  Although for simplicity, extinction is not included.}
are predicted \citep {2000ApJ...537..720L}
to be equal to the slopes of the 3D power spectra of their respective emissivities. 
However, only in the case of \oiii{} do we find this to be the case.
In the case of the other lines, \(\gamma_{\mathrm{vthick}}\) is shallower than
the emissivity's spectral index \(n\) by 0.36, 0.19, 0.61 for \ha, \nii, and \sii, respectively. 
The reason for this discrepancy may be the increasingly ``sheet-like'' morphology
of the emission in the lower ionization lines. 
As shown in \S~4.1 of \citet {2003ApJ...593..831M}, 
one should see a transition from \(\gamma_{\mathrm{vthick}} = n\) to the 
shallower slope \(\gamma_{\mathrm{vthick}} = n + 1\) at transverse scales larger
than the line-of-sight depth of the emitting region.


#+END_SRC
*** Plan of action
+ [-] Do a figure plotting the VCA-derived indices versus the real 3D index.
  + [X] Got the VCA index files from Jane
  + [X] Get the 3D index files
  + [X] Munge the data
  + [-] Make some plots
    + [X] Thick slices
    + [ ] Thin slices
+ [ ] Should do the same for the structure functions
**** Structure of the data
+ =Power-Indices/3D/${model}-${ion}-allfit.dat=
  + model :: '04052012_4_sp'
  + ion :: ['halp', 'oiii', 'niix', 'siix']
  + Columns to plot
    + Time :: $1
    + Index :: $5 - 2 
+ =Power-Indices/${view}/${model}-${bins}${thermal}-${line}kfit-tab.dat=
  + model :: '04052012_4_-sp'
  + view :: ['xy', 'xz', 'yz']
  + bins :: ['n032', 'n001'] - thin or thick
  + thermal :: ['y', 'n'] - yes or no
  + line :: ['Halpha', 'O35007', 'N26584', 'S26716'] 
  + Columns to plot
    + Time :: $1
    + Index :: $3
+ 
  + Columns to plot
    + Time :: $1
    + Index :: $3
**** DONE Mung all data into a big table
CLOSED: [2014-07-23 Wed 17:28]

#+name: extract-table
#+BEGIN_SRC python :return tab :results verbatim
  import json
  import numpy as np
  from astropy.table import Table

  views = ['xy', 'xz', 'yz']
  ions = ['halp', 'oiii', 'niix', 'siix', 'vion']
  lines = ['Halpha', 'O35007', 'N26584', 'S26716']

  binids = {'t': 'n032', 'T': 'n001'}

  results = {}
  columns = []
  for ion in ions:
      datafile = 'Power-Indices/3D/04052012_4_sp-{}-allfit.dat'.format(ion)
      times, k3d = np.loadtxt(datafile, usecols=(0, 4), unpack=True)
      if 't' in results:
          assert np.alltrue(times == results['t'])
      else:
          results['t'] = times
          columns.append('t')
      klabel = "_".join(['k3', ion[0].upper()])
      results[klabel] = k3d - 2.0
      columns.append(klabel)

  for ion, line in zip(ions[:-1], lines):
      for view in views:
          for tT, binid in binids.items():
              datafile = 'Power-Indices/' \
                         '{}/04052012_4_-sp-{}y-{}' \
                         'kfit-tab.dat'.format(view, binid, line)
              times, kvca = np.loadtxt(datafile, usecols=(0, 2), unpack=True)
              assert np.alltrue(times == results['t'])
              klabel = "".join(['kv', ion[0].upper(), tT, view])
              results[klabel] = kvca
              columns.append(klabel)

          datafile = 'Power-Indices/{}/04052012_4_{}-sfallfit.dat'.format(view, line)
          times, ksf = np.loadtxt(datafile, usecols=(0, 2), unpack=True)
          klabel = "".join(['ks', ion[0].upper(), view])
          results[klabel] = ksf
          columns.append(klabel)

  tab = Table(data=results, names=columns)
  tab.write('power-indices-vs-time.tab', format='ascii.tab')

#+END_SRC

#+RESULTS: extract-table
#+begin_example
 t     k3_H    k3_O    k3_N    k3_S  ... ksSxz    kvStyz    kvSTyz  ksSyz 
---- ------- ------- ------- ------- ... ------ --------- --------- ------
10.0 -3.5542 -3.8993 -2.4411 -2.3671 ... 0.4012  -1.90324 -1.993975 0.4523
11.0 -3.6413 -4.1279 -2.5538 -2.4154 ... 0.3447 -1.898838 -2.025668 0.4785
12.0 -3.3278 -3.8197 -2.5536 -2.4609 ... 0.3583 -1.954415 -2.120802 0.4667
13.0 -3.2569 -3.7877 -2.6925   -2.57 ... 0.3003 -1.810293  -1.96001 0.5195
14.0 -3.1404  -3.681 -2.7998 -2.6637 ... 0.2453 -1.737539 -1.923827 0.4134
15.0 -3.0544 -3.5216 -2.7767 -2.6313 ... 0.2633 -1.690619 -1.849246 0.4497
16.0 -3.0108 -3.4642 -2.7482 -2.6072 ...  0.255  -1.72312 -1.939087 0.4121
17.0 -3.0198  -3.483 -2.7795  -2.626 ... 0.2803 -1.692221  -1.85228 0.3539
18.0 -2.9295 -3.4211 -2.7144 -2.5929 ... 0.2899 -1.666025 -1.841816 0.3447
19.0 -2.8438 -3.3775 -2.6606 -2.5758 ... 0.2955  -1.67981 -1.806665 0.3359
20.0 -2.8162 -3.3462 -2.6547 -2.5706 ... 0.2774 -1.702789 -1.847767 0.3186
21.0 -2.8399 -3.3769 -2.6508 -2.5658 ... 0.2666 -1.704195 -1.844396 0.3056
22.0 -2.8374 -3.3242 -2.6624 -2.5775 ... 0.2224  -1.76931 -1.925681 0.2929
23.0 -2.8771 -3.3222 -2.6754 -2.5863 ... 0.2362  -1.76314 -1.933978 0.2755
24.0 -2.8784 -3.3163 -2.6901 -2.5963 ... 0.2657 -1.806039 -1.956009 0.2766
25.0 -2.8875  -3.294 -2.6855 -2.5741 ... 0.2781 -1.810989  -1.97014 0.2629
26.0 -2.9189 -3.3506 -2.7039 -2.5979 ...  0.292 -1.845024 -2.020894 0.2473
27.0 -2.9292 -3.3588 -2.7179 -2.6187 ... 0.2992 -1.839533 -1.991121 0.2482
28.0 -2.9401 -3.3405 -2.7153 -2.6051 ... 0.3253 -1.851696 -2.000542 0.2457
29.0 -2.9365 -3.3574  -2.727 -2.6234 ... 0.3763 -1.841143 -1.995638 0.2413
30.0 -2.9371 -3.2956 -2.7483 -2.6488 ...  0.409 -1.816146 -1.980373 0.2581
#+end_example
**** Common functions for graphs
#+name: power-indices-plot-setup
#+BEGIN_SRC python
  from astropy.table import Table
  from matplotlib import pyplot as plt
  tab = Table.read('power-indices-vs-time.tab', format='ascii.tab')

  linedict = {'O': '[O III] 5007', 'H': 'Ha 6563',
              'S': '[S II] 6716', 'N': '[N II] 6583'}
  color_from_view = {'xy': 'black', 'xz': 'gray', 'yz': 'lightgray'}
  symbol_from_view = {'xy': 'D', 'xz': 'o', 'yz': '>'}
  symbol_from_ion = {'O': 'o', 'H': 's', 'N': '>', 'S': 'D'}
  markerscale_from_symbol = {'o': 1.0, 's': 0.9, 'D': 0.9, '>': 1.1}
  markerscale_from_view = {'xy': 1.2, 'xz': 1.0, 'yz': 0.8}

  whitebox = {"fill": True, "fc": "white", "ec": "gray", "lw": 0.3, "alpha": 0.85, "boxstyle": "round,pad=0.2"}
  labelprops = dict(bbox=whitebox, ha='center', va='center', rotation_mode='anchor', fontsize='small')
#+END_SRC


#+name: power-indices-plot-kwds
#+BEGIN_SRC python
  plt_kwds = {
      "color": "black",
      "marker": symbol_from_view[view],
      "linestyle": '-',
      "markersize": 4.0*markerscale_from_view[view] \
          ,* markerscale_from_symbol[symbol_from_view[view]] 
  }
#+END_SRC

**** Plots for the thick VCAs
Try and split them up again says Jane - use 4 panels

#+BEGIN_SRC python :return pltfile :results file 
  <<power-indices-plot-setup>>

  tcut = 20.0

  fig, axes = plt.subplots(2, 2, sharex=True, sharey=True)
  plt.setp(axes.flat, aspect=1.0, adjustable='box-forced')
  kmin, kmax = -4.3, -1.5

  for ion, ax in zip('OHNS', axes.ravel()):
      k3 = tab['k3_' + ion]
      m = tab['t'] >= tcut
      mm = tab['t'] <= tcut
      ax.plot([kmin, kmax], [kmin, kmax], '-k')
      ax.plot([kmin, kmax], [kmin + 1, kmax + 1], '--k')
      ax.set_xlim(kmin, kmax)
      ax.set_ylim(kmin, kmax)
      # ax.vlines(-11./3., -100, 100, alpha=0.2, lw=3)
      ax.grid()
      for view in ['xy', 'xz', 'yz']:
          kthick = tab['kv' + ion + 'T' + view]
          kthin = tab['kv' + ion + 't' + view]
          <<power-indices-plot-kwds>>
          ax.plot(k3[mm], kthick[mm], alpha=0.2, label=None, **plt_kwds)
          ax.plot(k3[m], kthick[m], alpha=0.6,
                   label=linedict[ion] + ' ' + view,  **plt_kwds)
      ax.legend(loc='lower right', fontsize='small', ncol=1)

  for ax in axes[-1, :]:
      ax.set_xlabel(r'Power law index of 3D emissivity, $n$')
  for ax in axes[:, 0]:
      ax.set_ylabel(r'VCA power law index for thick slice: $\gamma_\mathrm{T}$')

  pltfile = 'vca-thick-vs-3d-panels.pdf'
  fig.set_size_inches((8.5, 8))
  fig.tight_layout()
  plt.savefig(pltfile)

#+END_SRC

#+RESULTS:
[[file:vca-thick-vs-3d-panels.pdf]]

**** Plot for the thin VCA

#+BEGIN_SRC python :return pltfile :results file 
  <<power-indices-plot-setup>>
  tcut = 17.0

  fig, axes = plt.subplots(2, 2, sharex=True)
  plt.setp(axes.flat, aspect=1.0, adjustable='box-forced')
  kmin, kmax = -3.8+0.01, -2.8-0.01

  for ion, ax in zip('OHNS', axes.flat):
      # if ion == 'H':
      #     continue
      k3 = tab['k3_V']
      m = tab['t'] >= tcut
      mm = tab['t'] <= tcut

      if ion in 'O':
          ax.plot([kmin, kmax], [-4.5 - 0.5*kmin, -4.5 - 0.5*kmax], '-k')
          ax.set_ylim(kmin+0.5, kmax+0.5)
      else:
          ax.plot([kmin, kmax], [-1.5 - 0.5*kmin, -1.5 - 0.5*kmax], '-k')
          ax.set_ylim(kmin+3.5, kmax+3.5)

      for view in ['xy', 'xz', 'yz']:
          kthick = tab['kv' + ion + 'T' + view]
          kthin = tab['kv' + ion + 't' + view]
          <<power-indices-plot-kwds>>
          ax.set_xlim(kmin, kmax)
          kplot = kthin if ion in 'O' else kthin - kthick
          ax.plot(k3[mm], kplot[mm], alpha=0.2, label=None, **plt_kwds)
          ax.plot(k3[m], kplot[m], alpha=0.6,
                   label=linedict[ion] + ' ' + view,  **plt_kwds)
      ax.vlines(-11./3., -100, 100, alpha=0.2, lw=3)
      ax.legend(loc='upper right', fontsize='small', ncol=1)
      ax.grid()
       
  for ax in axes[-1, :]:
      ax.set_xlabel(r'Power law index of 3D velocity, $n$', fontsize='small')
  for ax in axes[0, 0], :
      ax.set_ylabel(r'VCA power law index for thin slice: $\gamma_\mathrm{t}$', fontsize='small')
  for ax in axes[:, 1]:
      ax.yaxis.tick_right()
      ax.yaxis.set_label_position('right')
  for ax in axes[1, 0], axes[0, 1], axes[1, 1]:
      ax.set_ylabel(r'Difference between thin and thick slices: $\gamma_\mathrm{t} - \gamma_\mathrm{T}$', fontsize='small')

  pltfile = 'vca-thin-vs-3d-panels.pdf'
  fig.set_size_inches((9, 8))
  fig.tight_layout()
  plt.savefig(pltfile)

#+END_SRC

#+RESULTS:
[[file:vca-thin-vs-3d-panels.pdf]]

**** Plots for the structure function
#+BEGIN_SRC python :return pltfile :results file 
  <<power-indices-plot-setup>>


  tcut = 17.0

  fig, axes = plt.subplots(2, 2, sharex=True, sharey=True)
  plt.setp(axes.flat, aspect=1.0, adjustable='box-forced')
  kmin, kmax = -3.8+0.01, -2.8+0.01

  for ion, ax in zip('OHNS', axes.flat):
      k3 = tab['k3_V']
      m = tab['t'] >= tcut
      mm = tab['t'] <= tcut
      ax.plot([kmin, kmax], [-3 - kmin, -3 - kmax], '--k')
      ax.plot([kmin, kmax], [-2 - kmin, -2 - kmax], '-k')
      loc = 'lower left' if ion in 'HO' else 'upper left'
      ax.vlines(-11./3., -100, 100, alpha=0.2, lw=3)
      ax.grid()
      for view in ['xy', 'xz', 'yz']:
          ksf = tab['ks' + ion + view]
          <<power-indices-plot-kwds>>
          ax.plot(k3[mm], ksf[mm], alpha=0.2, label=None, **plt_kwds)
          ax.plot(k3[m], ksf[m], alpha=0.6,
                   label=linedict[ion] + ' ' + view,  **plt_kwds)
          ax.set_xlim(kmin, kmax)
          ax.set_ylim(kmin+3.9, kmax+3.9)
      ax.legend(loc=loc, fontsize='small', ncol=1, fancybox=True)
      ax.annotate(r'$n = -11/3$', (-11/3, 0.45), rotation="vertical", **labelprops)
      ax.annotate(r'$m_{\mathrm{2D}} = m_{\mathrm{3D}} + 1$', (-2.95, -2 - (-2.95)),  rotation=-45, **labelprops)
      ax.annotate(r'$m_{\mathrm{2D}} = m_{\mathrm{3D}}$', (-3.4, -3 - (-3.4)),  rotation=-45, **labelprops)

  for ax in axes[-1, :]:
      ax.set_xlabel(r'Power law index of 3D velocity, $n$', fontsize='small')
  for ax in axes[:, 0]:
      ax.set_ylabel(r'Structure function power law index: $m_\mathrm{2D}$', fontsize='small')

  pltfile = 'sf-vs-3d-panels.pdf'
  fig.set_size_inches((8.5, 8))
  fig.tight_layout()
  plt.savefig(pltfile)

#+END_SRC

#+RESULTS:
[[file:sf-vs-3d-panels.pdf]]

**** some emoji
😦☹🙍👒👊✊👎👍👌👭🙋👬👫🙏🙌

** Other suggestions
*** Figure 4
Plot from an earlier time (50,000 years)
*** Figure 5
Caption: R is the radius of an equivalent sphere with volume equal to that of the H II region
*** TODO Definition of wavenumber, k
:LOGBOOK:
- Note taken on [2014-07-26 Sat 17:32] \\
  Need to export this to sec 3.2.1
:END:
Insert after first sentence of 3.2.1
#+BEGIN_SRC latex
In the following sections we use a dimensionless \(k\) that is normalised to the size of our computational grid.  Thus \(k = 1\) corresponds to a physical scale of \(4\)~pc. 
#+END_SRC
** QUOTE Entire report 
Date: Mon, 3 Mar 2014 05:17:30 -0500 (EST)
From: ae@ras.org.uk
To: j.arthur@crya.unam.mx
Cc: s.serrano@crya.unam.mx, j.arthur@crya.unam.mx, w.henney@crya.unam.mx,
    garrelt@astro.su.se, a.gazol@crya.unam.mx
Subject: OutSRV MNRAS: MN-13-3354-MJ

Dear Dr Arthur

Copied below are the reviewer's comments on your manuscript entitled "Turbulence in simulated HII regions", ref. MN-13-3354-MJ, which you submitted to Monthly Notices of the Royal Astronomical Society.

Moderate revision of your manuscript is requested before it is reconsidered for publication.

You should submit your revised version, together with your response to the reviewer's comments via the Monthly Notices ScholarOne Manuscripts site http://mc.manuscriptcentral.com/mnras.
Enter your Author Centre, where you will find your manuscript title listed under "Manuscripts with Decisions."  Under "Actions," click on "Create a Revision."  Your manuscript reference will be appended to denote a revision.

IMPORTANT: do not submit your revised manuscript as a new paper!

You will not be able to make your revisions to the originally submitted files of the manuscript held on ScholarOne Manuscripts.  Instead, you must delete the original files and abstract and replace them with your revised files.  Check that any requests for colour publication or online-only publication are correct.  Proof read the resulting PDF and HTML files that are generated carefully. If you have used a .bib file to generate your bibliography in Latex, please include this in your .tar archive along with the .bbl and .tex files; this will aid the editing and typesetting process.

When submitting your revised manuscript, you will be able to respond to the comments made by the reviewer in the space provided.  You should also use this space to document any changes you make to the original manuscript.  In order to expedite the processing of the revised manuscript, please be as specific as possible in your response to the reviewer.  It would also be very helpful if you could highlight the changed sections, e.g. by the use of colour, colour highlighting or bold typeface - this will not delay in any way the subsequent processing of your paper.

Because we are trying to facilitate timely publication of manuscripts submitted to MNRAS, your revised manuscript should be uploaded promptly. If you do not submit your revision within six months, we may consider it withdrawn and request it be resubmitted as a new submission.

Please note that, due to the tight schedule, any post-acceptance changes notified after the paper has gone into production (i.e. the day after the acceptance email is sent) cannot be incorporated into the paper before it is typeset. Such changes will therefore need to be made as part of the proof corrections. To avoid excessive proof corrections and the delay that these can cause, you are strongly encouraged to ensure that each version of your paper submitted to MNRAS is completely ready for publication!

I look forward to receiving your revised manuscript.

Regards,

Anna

Anna Evripidou
Assistant Editor
"Monthly Notices" and "Geophysical Journal International"
Royal Astronomical Society
Email: ae@ras.org.uk
Tel: (+44) 01483 427 583
Tel (Wednesdays): (+44) 020 7734 3307
Fax: (+44) 020 7287 2167

========================================================

Reviewer's Comments:

Comments to the Author

Review of Serrano-Medina et al.

This paper examines how different diagnostics of turbulent flows in H II regions respond to application to a simulated H II region. It concludes that velocity channel analysis provides a more reliable way of recovering the actual velocity structure than traditional velocity centroid structure functions.  This seems like an interesting and useful result that is worth publishing.

The paper suffers, however, from minor problems that need to be cleaned up before publication. The general theme is that the presentation needs to be tightened up and made more transparent and consistent. I now describe specific issues, generally in the order that they appear in the paper.  The last of these is arguably the most important.

1. It should be made clear at the beginning of section 2 (Numerical Models) that the initial conditions are unstable to gravitational collapse (free-fall time of 0.6 Myr), but that self-gravity is neglected for these relatively short time runs.

2. In the discussion of power spectra (3.2), the time behavior of the power law is compared to that of the velocity dispersion.  A time delay of 50,000 yrs is noted, with no further discussion.  The time delay would seem to suggest that the two quantities are unrelated; either that conclusion should be made explicit, or the time delay should be more explicitly discussed as related (perhaps in relation to the following paragraph?)

3. In Figure 3 and following, I think quoting the slopes on the figure rather than in a separate table would make the information more accessible.

4. Presenting the time behavior of the slopes in a Figure rather than a table, as was done in Figure 4, also vastly improves the comprehensibility of the result.  I would suggest replacing the tables generally with figures, as the actual values are less important than the trends seen.

5. The infinitesimal "inertial ranges" seen in some of the panels of Figure 6 & 7, particularly for [S II], need further consideration.  Is the criterion being used for the upper bound robust for these rather filamentary, intermittent, emission sources?

6. Similarly, further thought and discussion as to the meaning of the entire box being correlated to itself (structure function < 2 everywhere) might well yield a deeper understanding.

7. At the end of 3.2.2, what is the meaning of a break at 0.3 pc?  Does it have observational or physical correlates?

8. The crucial section 3.2.3 on the superiority of the VCA needs work.  It refers to data not presented on the intermediate velocity slices; it uses a pagelong table rather than a figure to present the information needed (as I noted above); and as a result doesn't clearly make the correct that thermal broadening destroys the value of the thin slices. (Is this indeed still true for the heavier, narrower, ions?)

9. The caption of the accompanying Figure 9 does not agree with the figure: it refers to non-existent open squares; the dashed line fits to the crosses, not the non-existent squares; and the thickness of the slice doesn't seem to agree with the number of channels.  It also doesn't specify which of the three axes is presented, though the accompanying table presents all three axes.

10. In section 4.1.1, an opposition is presumed between numerical dissipation and vortex center dissipation as proposed by She & Leveque.  However, a well-resolved numerical model will have numerical dissipation occurring in the centers of the vortexes, and should reproduce She & Leveque's results.  So to make the argument, you need to argue that your models are particularly poorly resolved...

11. In section 4.1.2, what is the implication of ruling out the Kolmogorov value of the turbulence power law?  That is dropped into the discussion without a conclusion being drawn.

12. The crucial section 4.1.3 is where the VCA is demonstrated to work better than other methods. However, it is curiously anecdotal.  Given that the abstract and conclusion present this as the central point of the paper, use should be made of the vast amount of data presented for the VCA in Figure 9 and Table 3, to make a much more systematic comparison with the actual power spectra known from the 3D model.

I do apologize to the authors for the delay in completing this report.

* Abstract
#+BEGIN_SRC latex
  We investigate the scale dependence of fluctuations inside a realistic
  model of an evolving turbulent \hii{} region and to what extent these
  may be studied observationally.  We find that the multiple scales of
  energy injection from champagne flows and the photoionization of
  clumps and filaments leads to a flatter spectrum of fluctuations than
  would be expected from top-down turbulence driven at the largest
  scales.  The traditional structure function approach to the
  observational study of velocity fluctuations is shown to be
  incapable of reliably determining the velocity power spectrum of our
  simulation.  We find that a more promising approach is the Velocity
  Channel Analysis technique of Lazarian \& Pogosyan (2000), which,
  despite being intrinsically limited by thermal broadening, can
  successfuly recover the logarithmic slope of the velocity power
  spectrum to a precision of \(\pm 0.1\) from high resolution optical
  emission line spectroscopy.
  
#+END_SRC

* Summary and Conclusions
#+BEGIN_SRC latex
  \begin{enumerate}
  \item We have investigated the statistics of fluctuations in physical
    conditions within a radiation hydrodynamic simulation of the
    evolution of an \hii{} region inside a highly inhomogeneous
    molecular cloud.  We find that steady-state turbulence,
    corresponding to time-independent profiles of the 3D power-spectra, is
    only established after about 1.5 sound-crossing times of the \hii{}
    region. In these simulations, this corresponds to about 200,000
    years.
  \item We find a power law behavior for the 3D power spectra in the
    range from about 1 pc down to 0.125 pc, equivalent to 16
    computational cells. The larger scale can be interpreted as the size
    of the largest photoevaporated flows, while the smaller scale is
    about twice the numerical dissipation scale.  The power spectrum
    slopes of the velocity and density fluctuations are very similar and
    always lie in the range \(-3.1 \pm 0.1\).  This is significantly
    shallower than the slope predicted for the inertial range of either
    incompressible or compressible turbulence (\(-3.667 \to -4.1\)).
    This suggests that turbulent driving is occuring over all scales in
    our simulation, unlike the case of classical turbulence where energy is
    injected only at the largest scales.  The power spectrum slopes of
    the emissivities of optical lines are even shallower, increasingly so
    for lower ionization lines, indicating that the smallest scale
    fluctuations are dominant.
  \item We investigate in detail the utility of observational
    diagnostics for inferring the power spectra of emissivity and
    velocity fluctuations in our simulation.  We find that the
    traditional velocity centroid structure function technique gives
    ambivalent results because of the effects of projection smoothing,
    combined with the fact that the effective line of sight depth of the
    emitting gas does not have a single well-defined value.  In
    addition, the presence of anisotropic motions such as champagne
    flows can yield misleading structure function slopes when the
    simulation is viewed from certain directions.
  \item The more recently developed technique of Velocity Channel
    Analysis is found to offer a more robust diagnostic of the
    three-dimensional velocity statistics of our simulation.  The slope
    of the velocity power spectrum can be correctly recovered to a precision
    of \(\pm 0.1\) from either high or low ionization lines, and with no
    significant dependence on viewing direction.
  \end{enumerate}
#+END_SRC

* Observational turbulence studies
+ GENERAL
  + Disparate results
  + Varying methodology
    + whether or not to use separate velocity components
    + whether or not to subtract out large-scale systematic velocity gradients
+ Miville-Deschenes (1995ApJ...454..316M)
  + Do the autocorrelation function and the structure function
    + But they fit and remove a fourth order polynomial first!
    + This should only affect the largest scales (> 1 pc in their case)
    + They find a completely flat strucfunc for scales > 0.07 pc
    + And and about L^{0.6} for smaller scales (by eye from the graph)
  + They also calculate a \sigma-size relation
    + This shows \sigma \sim L^{0.3} over 0.1 \to 10 pc, which is strangely inconsistent with the strucfunc
    + They do say that the dispersion-size relation does not necessarily indicate turbulence
+ Lagrois & Joncas (2011MNRAS.413..721L)
  + Study a giant extragalactic HII region
  + Find a steepish structure function up to 50 pc
  + But actually the slopes are somewhat like ours
  + \sigma_c = 6, 8, 5 km/s for H\alpha, [O III], [S II]
  + => \sigma_c^2 = 36, 64, 25
  + cf. our values of 10, 16, 13 

+ O'Dell & Wen (1992ApJ...387..229O)
  + [O I] line
    + They do not remove any gradients
    + They do correct for instrumental width
      + B(r) = B_0(r) - 2 v_ins^2, where v_ins = 0.516 km/s
      + Their smallest B(r) is 1 km^2/s^2 so this hardly affects the results
  + Structure function has slope of 0.68 from 6.25 to 85 arcsec
    + 0.013 to 0.177 parsec
  + Also measure linewidth-size relation, finding slope of 0.41
  + These are more-or-less consistent with a Kolmogorov-type slope of
    + 0.667 for struc func
    + 0.333 for linewidth-size (less good agreement here)
  + Since the [O I] layer is so thin, there should be no projection smoothing to speak of
+ O'Dell & Castañeda (1987ApJ...317..686O)
  + Summarise many HII regions
+ Most comprehensive study
  + Curves are all over the place
  + But find that structure functions are much flatter than Kolmogorov
  + Best fit is with v independent of L
+ Castañeda 1988 (1988ApJS...67...93C)
  + [O III] from Orion
  + Fits 3 velocity systems A, B, C (C is scattered)
  + Finds turnover in the struc func around 10 \to 20 arcsec, 0.02 parsec
+ Wen & O'Dell (1993ApJ...409..262W)
  + [S III] from Orion
  + Fits multiple systems but only analyses brightest
  + Turnover in struc func is at 30 arcsec, 0.04 parsec



** Text for Jane
#+BEGIN_SRC latex
  \textit{First paragraph as is, but mention the Orion [\ion{S}{3}] and
    [\ion{O}{1}] studies.}
  
  Observational studies of the spatial scales of velocity fluctuations 
  have mostly focused on the structure function of velocity centroids.  
  The results are rather disparate, partly because the methodology varies
  considerably between different studies. 
  For instance, some authors attempt to filter out ``ordered'' large scale motions
  before analysing the fluctuations \citep{1995ApJ...454..316M, 2011MNRAS.413..721L},
  whereas others analyse the unfiltered observations \citep{1992ApJ...387..229O, 1997ApJ...487..163M}.
  Also, in some cases multiple Gaussian velocity components are fitted to the line profiles
  \citep{1988ApJS...67...93C, 1993ApJ...409..262W},
  which are then assigned to a small number of velocity ``systems'' that are each analysed separately,
  whereas in most studies the mean velocity of the entire line profile is used. 
  
  Despite these differences, there are interesting commonalities in the results:
  a rising structure function with \(m_{\mathrm{2d}} = 0.5\)--\(1.0\) 
  is nearly always found at the smallest scales,
  which transitions to a flat structure function with \(m_{\mathrm{2d}} \sim 0\) at larger scales. 
  However, the scale at which the transition occurs varies enormously from object to object,   
  from \(0.02\)--\(0.2\)~pc in compact (\(R = 1 \to 5\)~pc) Galactic \hii{} regions
  \citep{1987ApJ...317..676O, 1988ApJS...67...93C, 1993ApJ...409..262W, 1995ApJ...454..316M},
  up to 50~pc in giant (\(R \sim 400\)~pc) extragalactic regions \citp{2011MNRAS.413..721L}.\footnote{
    Such giant \hii{} regions show velocity centroid dispersions of
    \(\sigma_{\mathrm{c}} > 10~\mathrm{km\ s^{-1}}\) on the largest scales,
    which is several times larger than is seen in compact single-star regions
    or in our simulations.  We will therefore not consider them further since they are 
    governed by additional physical processes, such as powerful stellar winds and the 
    cluster gravitational potential, which are beyond the scope of the current paper.
  }
  
  The explanations that have been offered for the break in the structure function slope are also varied.
  In the case of compact \hii{} regions, it is often taken to indicate the
  characteristic line-of-sight depth of the emission zone \citep{1951ZA.....30...17V, 1987ApJ...317..686O},
  with projection smoothing steepening the slope at the smaller separations
  (see \S~{sec:projection-smoothing} above). 
  If that were the case, then the correct three-dimensional structure function slope is the flat one:
  \(m_{\mathrm{3d}} \sim 0\), corresponding to a velocity power spectrum slope of \(n = -3\). 
  This interpretation would be broadly consistent with our simulation results, 
  which show a very similar velocity power spectrum (Fig.~\ref{fig:power-spectra}).
  However, our simulated structure functions rarely show a clear break in the same way as the observations do,
  although they do show a slight negative curvature in many cases.
  This is probably because of the very limited useful dynamic range, roughly a factor of 10, 
  that the simulations allow between the small scales that are affected by numerical diffusion
  and the large scales, that are affecetd by systematic flows, anisotropies, and edge-effects. 
  
  An alternative explanation for the observed break in the structure function is that
  it represents the scale of the largest turbulent eddies
  \citep{1988ApJS...67...93C, 1995ApJ...454..316M}
  and that the fluctuations at larger scales are simply uncorrelated.  
  In such a picture it would still be necessary to postulate a velocity spectrum
  considerably shallower than Kolmogorov in order to explain the small-scale slope. 
  
  Based on the discussion of our simulation results above (\S~\ref{sec:will-discuss}),
  it seems that Velocity Channel Analysis would be a very useful complement to the structure function,
  since it is less affected by uncertainties in projection smoothing
  and gives a more consistent result between different emission lines 
  (at least, for our simulations).
  
  In a forthcoming paper, we will present such an analysis of recent
  high-resolution echelle spectroscopy of multiple emission lines in the Orion Nebula
  \citep{2008RMxAA..44..181G, 2008AJ....136.1566O}
  
  
#+END_SRC
** The "problem of the line widths"
+ What do they mean by this?
  + Supposedly the structure function implies a smaller FWHM than is observed

* Figure caption
#+BEGIN_SRC latex
  \begin{figure}
    \centering
    \includegraphics{o3-thick-thin}
    \caption{Surface brightness maps in thick (left) versus thin (right) 
      velocity slices for the \oiii{} line from our simulation
      at an age of 300,000~years.  
      The thick slice covers the full velocity range of the emission line,
      while the thin slice has a width of 5~\kms{},
      which is smaller than the turbulent velocity fluctuations,
      but slightly larger than the thermal broadening for this line.
      It is apparent that the thin slice shows considerably greater
      small-scale structure than the thick slice,
      which is reflected in its shallower power spectrum.
      The brightness structure in the thick slice is due entirely to
      the emissivity fluctuations within the \hii{} region, 
      whereas the additional structure in the thin slice is caused by
      velocity fluctuations.
    }
    \label{fig:o3-thick-thin}
  \end{figure}
#+END_SRC
* Latex material for discussion
#+BEGIN_SRC latex
  \newcounter{ionstage}
  \newcommand{\ion}[2]{\setcounter{ionstage}{#2}% 
    \ensuremath{\mathrm{#1\,\scriptstyle\Roman{ionstage}}}}
  \newcommand\nii{[\ion{N}{2}]}
  \newcommand\sii{[\ion{S}{2}]}
  \newcommand\oiii{[\ion{O}{3}]}
  \newcommand\ha{\ensuremath{\mathrm{H\alpha}}}
  \newcommand\hii{\ion{H}{1}}
  
  % INTRINSIC POWER SPECTRA OF PHYSICAL QUANTITIES
  Figure~\ref{fig:intrinsic-power-spectra} shows that
  the power spectra of physical quantities are very well approximated
  by power laws over the range from \(k = 4 \to 32\)
  (scales of 1~pc to 0.125~pc).
  In particular, the ionized gas velocity shows
  a power law slope of \(\mu = -3.2 \pm 0.1\)
  once the turbulence is fully developed. 
  This is significantly shallower than the Kolmogorov (\(\mu = -3.667\))
  or Burgers (\(\mu = -4\)) value,
  indicating more velocity structure at small scales than would be seen
  in a simple turbulent cascade of energy injected at the largest scale.
  One reason for this may be that energy is injected over a variety of scales.
  As a consequence,
  the turbulent velocity dispersion is relatively insensitive to scale,
  varying as \(\sigma \sim L^{0.5 (-3 - \mu)} \sim L^{0.01}\). 
  
  The density has a very similar slope to the velocity: \(n = -3.2 \pm 0.1\),
  but of greater relevance
  are the slopes of the emissivities of the different emission lines,
  which are \(n = -3.4 \pm 0.1\) for \oiii{}, 
  \(n = -2.9 \pm 0.1\) for \ha,
  \(n = -2.7 \pm 0.1\) for \nii, and
  \(n = -2.6 \pm 0.1\) for \sii.
  These span the critical value of \(n = -3\)
  that divides ``steep'' from ``shallow'' power spectra.
  \oiii{} has a steep slope,
  indicating that large-scale fluctuations dominate,
  while \nii{} and \sii{} have shallow slopes,
  indicating that small-scale fluctuations dominate. 
  The \ha{} slope is very close to the critical value,
  indicating roughly equal contributions from fluctuations on all size-scales.
  
  % DETERMINING \mu AND n FROM OBSERVATIONAL DIAGNOSTICS
  It is interesting to study the question of whether
  the known power law indices of the velocity and emissivity power spectra in our simulations
  can in practice be recovered from observational diagnostics.  
  If this is not the case for a given diagnostic,
  then it would call into question its utility for studying real \hii{} regions.
  In particular, we will concentrate on two commonly used diagnostics:
  the second-order structure function of the line velocity centroids,
  and the power spectra of the surface brightness in isovelocity channel maps
  (Velocity Channel Analysis). 
  
  % STRUCTURE FUNCTION
  The structure function of the velocity centroids is an observationally attractive diagnostic
  because it is relatively immune to the effects of thermal broadening 
  and poor spectral resolution,
  so long as sufficiently high signal-to-noise spectra are used. 
  However, it has the disadvantage that relating the observed slope 
  to the 3-dimensional velocity statistics depends on the geometry
  of the emitting region, see \S~\ref{sec:projection-smoothing}. 
  For transverse separations larger than
  the characteristic line-of-sight depth of the emitting gas,
  the two-dimensional gradient should be equal to the three-dimensional one:
  \[
  m_{\mathrm{2D}} = m_{\mathrm{3D}} = -3 - \mu,
  \]
  whereas at smaller separations than this, 
  projection smoothing, as described above, means that 
  the two-dimensional gradient is steeper:
  \[
  m_{\mathrm{2D}} = 1 + m_{\mathrm{3D}} = -2 - \mu.
  \]
  Based on our simulation's velocity power spectrum index of \(\mu \approx -3.2\), 
  the structure function slope should be \(m_{\mathrm{2D}} = 0.2\) in the large-scale limit
  and \(m_{\mathrm{2D}} = 1.2\) in the small-scale limit. 
  
  In fact, all of the measured slopes lie between these two limits,
  with a systematically increasing value from low to high-ionization lines:
  \(m_{\mathrm{2D}}(\sii) = 0.45 \pm 0.01\), 
  \(m_{\mathrm{2D}}(\nii) = 0.55 \pm 0.02\), 
  \(m_{\mathrm{2D}}(\ha) = 0.60 \pm 0.03\), 
  \(m_{\mathrm{2D}}(\oiii) = 0.75 \pm 0.03\). 
  This is qualitatively consistent with expectations
  because the emission from lower-ionization lines is confined to 
  thin layers near the ionization front, whereas higher ionization emission
  is more distributed over the volume
  and therefore subject to greater projection smoothing.
  
  If the line-of-sight depth were constant over the face of the \hii{} region,
  then the structure function would show a break at that scale,
  but in reality the depth varies from point to point, 
  so the break will be blurred out.
  Instead, the structure function is expected to show negative curvature,
  with the gradient gradually decreasing 
  as one passes from smaller to larger scales. 
  A small such effect is seen in the structure functions 
  derived from our simulations (Fig.~\ref{fig:strucfunc-x} to \ref{fig:strucfunc-z}):
  the fit to a power law is generally not so good as in the case of the power spectra,
  with negative residuals at both ends of the fitted range,
  indicative of a negative curvature.  
  That the observed effect is so small is probably due to the fact that
  the distribution of line-of-sight depths strongly overlaps with 
  the limited dynamic range in separations available from our simulations,
  bounded at small scales by numerical dissipation,
  and at large scales by the size of the ionized region.
  
  It is disappointing that none of the measured slopes
  reach either of the limiting cases discussed above.
  All that can be deduced from the structure function is that 
  \(1 + m_{\mathrm{3D}} > m_{\mathrm{2D}}(\oiii)\) 
  and \(m_{\mathrm{3D}} < m_{\mathrm{2D}}(\sii)\), which implies \(\mu = -2.75 \to -3.45\).
  Although this is a rather wide range of allowed velocity power spectrum slopes,
  it does serve to rule out the Kolmogorov value of \(\mu = -3.667\). 
  
  A further proviso to the use of the structure function is that
  systematic anisotropic flows can affect the measured slopes
  when the viewing angle is along the direction of the flow.
  Such an effect is seen at later times for our simulation
  when viewed along the \(x\)-axis (Fig.~\ref{fig:strucfunc-x}). 
  In this case, the structure function tends to steepen
  at the large-scale end of our fitting range,
  producing a positive curvature, 
  which is opposite to the more typical case of negative curvature discussed above.
  Such cases may also be identified by the presence of a significant skew
  in the PDF of the line-of-sight velocity (see Fig.~\ref{fig:velocity-PDFs}).
  
  Note that the additional complication identified by \citet{Brunt:2004a}, 
  whereby correlations between density and velocity fluctuations affect the 
  translation between \(m_{\mathrm{2D}}\) and \(\mu\), 
  is likely of minor importance in our case.  
  \citet{Esquivel:2007b} show that this is most important
  for high Mach number turbulence, where \(\delta\rho/\langle \rho \rangle > 1\),
  whereas the transonic turbulence inside our simulated \hii{} regions
  produces more modest density contrasts. 
  
  % VCA
  The velocity channel analysis consists of calculating the
  two-dimensional power spectrum of the brightness distribution
  in isovelocity channels of varying thickness.  
  We consider two cases: thick slices,
  which are wide enough (\(\sim 100~\mathrm{km\ s^{-1}}\))
  to include all the emission in the line,
  and thin slices, with width \(5~\mathrm{km\ s^{-1}}\). 
  Because the velocity spectrum in our simulations is rather shallow (see above),
  the line-of-sight turbulent velocity dispersion \(\delta v\)
  exceeds the width of these thin slices
  over the full range of length scales that we can usefully study,
  from \(0.1\)~pc (\(\delta v \approx 8~\mathrm{km\ s^{-1}}\))
  to \(1\)~pc (\(\delta v \approx 10~\mathrm{km\ s^{-1}}\)). 
  
  To use thinner slices would not be useful for a variety of reasons.
  First, \(5~\mathrm{km\ s^{-1}}\) corresponds to the highest resolution 
  that can be achieved with optical spectrographs
  that are optimised for studying extended sources,
  such as Keck HIRES or VLT UVES. 
  Second, thinner slices are increasingly subject to ``shot noise'' 
  due to the finite resolution of the numerical simulations,
  which produces spurious small-scale power, as discussed by 
  \citet{Esquivel:2003a} and \citet{Miville-Deschenes:2003a}.
  Third, thermal broadening would smoothe out any structure on 
  scales \(< 5~\mathrm{km\ s^{-1}}\) for all but the heaviest ions.
  
  The procedure for deriving the power law index
  of the velocity fluctuations from the velocity channels is
  slightly different, depending on whether the power spectrum 
  of the emissivity fluctuations is ``steep'' or ``shallow'' (see above). 
  In the steep case, which applies to \oiii{} in our simulation, 
  the slope of the average power spectrum of the brightness maps
  in the thin isovelocity channels is given by 
  \(\gamma_{\mathrm{thin}} = -3 + \frac12 m_{\mathrm{3D}}\),
  where \(m_{\mathrm{3D}} = -3 - \mu = 0.2 \pm 0.1\) for our simulation.
  The derived value from the \oiii{} thin channel maps is 
  \(\gamma_{\mathrm{thin}} = -2.84 \pm 0.11 \),
  which compares very well with the value \(-2.9 \pm 0.05\)
  that is implied by the simulation's value of \(\mu\). 
  
  In the shallow case, it is the difference in slope
  between the thin and thick slices
  that is predicted to depend on the velocity fluctuations:
  \(\gamma_{\mathrm{thin}} - \gamma_{\mathrm{thick}} = \frac12 m_{\mathrm{3D}}\). 
  The derived values are 
  \(\gamma_{\mathrm{thin}} - \gamma_{\mathrm{thick}} = 0.08 \pm 0.04\), 
  \(0.18 \pm 0.04\), and \(0.18 \pm 0.04\)
  for \ha, \nii, and \sii, respectively. 
  These also compare well with the value of \(0.1 \pm 0.05\)
  that is implied by the simulation's value of \(\mu\). 
  
  The slopes of the power spectra of the thick slices themselves, 
  which are simply the velocity-integrated surface brightness images\footnote{
    Although for simplicity, extinction is not included.}
  are predicted \citep{Lazarian:2000a}
  to be equal to the slopes of the 3D power spectra of their respective emissivities. 
  However, only in the case of \oiii{} do we find this to be the case.
  In the case of the other lines, \(\gamma_{\mathrm{thick}}\) is shallower than
  the emissivity's \(n\) by 0.36, 0.19, 0.61 or \ha, \nii, and \sii, respectively. 
  The reason for this discrepancy may be the increasingly ``sheet-like'' morphology
  of the emission in the lower ionization lines. 
  As shown in \S~4.1 of \citet{Miville-Deschenes:2003a}, 
  one should see a transition from \(\gamma_{\mathrm{thick}} = n\) to the 
  shallower slope \(\gamma_{\mathrm{thick}} = n + 1\) at transverse scales larger
  than the line-of-sight depth of the emitting region.
  
#+END_SRC


* Conclusions
** DONE Intrinsic power spectra of physical quantities
CLOSED: [2013-12-14 Sat 17:40]
+ [X] We have good power laws over a reasonable range
+ [X] Ionized gas velocity has slope \mu = -3.2 \pm 0.1 once the turbulence is fully developed
  + This rather shallow compared with Kolmogorov (\mu = -3.667) or Burgers (\mu = -4.0), implying relatively more velocity structure at smaller scales than is seen in an inertial cascade
  + One reason for this may be the injection of energy at all scales
  + The associated autocorrelation slope of u^2 (or second-order structure function slope) is m = -3 - \mu = 0.2 \pm 0.1, where \delta{}u \sim L^{m/2}
  + So u \sim L^{0.1 \pm 0.05}, which is remarkably shallow.  It means that with \sigma \approx 10 km/s on scale of 1 pc, we will still have \sigma = 8 km/s on scale of 0.1 pc
+ [X] Density has slope n = -3.2, same as velocity, but more relevant are emissivity slopes: n = -2.9 \pm 0.1 for H\alpha and n = -3.4 \pm 0.1 for [O III]
** DONE We want to see if we can diagnose the intrinsic power spectrum from observables
CLOSED: [2013-12-13 Fri 17:55]
+ In particular the power law index of the ionized gas velocity power spectrum, which is -3.2 \pm 0.1 in our simulations
+ Can it be deduced from the /Structure Function/ or the /Velocity Channel Analysis/?
*** DONE Structure function
CLOSED: [2013-12-14 Sat 16:28]
+ [X] has big advantage that it is relatively immune to effects of thermal broadening and poor instrumental resolution, so can be used for H\alpha
+ big disadvantage that it has the uncertainty of projection smoothing
  + [X] smoothing should apply at scales smaller than the characteristic line-of-sight depth of the emitting gas
  + [X] would give a break of magnitude \delta{}m = 1 in the spectrum (steeper at smaller scales, where the smoothing operates)
  + [X] except that the line-of-sight depth has a distribution, rather than a fixed value, since it varies from point to point, so that instead of a break, we should see a negative curvature to the structure function over the fitted range
  + [X] Just such curvature is seen (mostly)
  + [X] In addition, we see a clear progression from [S II] \to [N II] \to H\alpha \to [O III]
    + m_{2D}([S II]) = 0.45 \pm 0.01
    + m_{2D}([N II]) = 0.55 \pm 0.02
    + m_{2D}(H\alpha) = 0.60 \pm 0.03
    + m_{2D}([O III]) = 0.75 \pm 0.03
  + [X] Based on the simulation's velocity power spectrum index of \mu \approx -3.2, this should have a value between:
    + m_{2D} = 0.2 (no smoothing), and
    + m_{2D} = 1.2 (full smoothing)
  + [X] The results are obviously consistent with this, and seem to follow a consistent trend with less smoothing (shallower spectrum) where the emission is more sheet-like ([S II]), progressing to more smoothing where the emission is more diffuse ([O III])
  + [X] But nothing is clearly in any particular limit, so it is hard to infer \mu from the observations
    + The limits are 1 + m_3D > 0.75 \pm 0.03 and m_3D < 0.45 \pm 0.01
    + => m_3D = -0.25 \to 0.45 => \mu = 2.75 \to 3.45 = 3.1 \pm 0.35
    + Although this does rule out Kolmogorov: \mu = 3.667
  + [X] PLUS added complication of the Brunt & Mac Low (2004) effect, where density (emissivity) fluctuations correlated with the velocity fluctuations can effect the velocity centroid distributions and partially or fully cancel out the projection smoothing effect
    + For a compressible flow, the structure function of the velocity centroids is not solely a function of the POS variation of the LOS velocity, as it is in the incompressible case.  Instead, there will be a contribution from the interaction of the LOS variations of LOS velocity with LOS+POS variations of emissivity
    + But Lazarian (2007) say that this depends on \delta\rho
  + [X] PLUS AGAIN it is affected by champagne flows along line of sight, which steepen the structure function without any concommitant change in \mu
    + This happens mainly at the larger separations in the fitting range, which gives it a positive curvature, allowing it to be potentially spotted.  Another telltale sign is a shoulder on the velocity PDF
*** TODO VCA
+ [X] We use 5 km/s slices as the thin limit
  + This is the highest resolution that can regularly be achieved with current echelle spectrographs
  + Also, thermal broadening means that most lines would not benefit from going to higher resolution
  + And smaller slices also run into problems with discretization noise in the simulations that produces spurious small-scale power, as discussed by Esquivel
+ [X] The thick slices should have an index \gamma_{thick} equal to the power law index n of the 3D power spectrum of the line emissivity in all cases (/but are we really sure of this/):
  + [O III]: \gamma_{thick} = -3.33 \pm 0.03, n = -3.4 \pm 0.1 /YES/
  + H\alpha:  \gamma_{thick} = -2.59 \pm 0.02, n = -2.95 \pm 0.15 /PCA thick slope is too shallow!/
  + [N II]: \gamma_{thick} = -2.51 \pm 0.03, n = -2.7
  + [S II]: \gamma_{thick} = -1.99 \pm 0.03, n = -2.6
+ [X] The thin slices, with width < \delta{}v(k), should have a shallower slope \gamma_{thin}, which depends on the velocity fluctuations \mu, or equivalently m = -3 - \mu
+ [X] There are two cases:
  + [X] steep emissivity, n < -3, appropriate to [O III]: \gamma_{thin} = -3 + m/2
    + [O III]: \gamma_{thin} = -2.84 \pm 0.11, -3 + m/2 = -2.9 /YES/
  + [X] shallow emissivity, n > -3, appropriate to the other lines:  \gamma_{thin} - \gamma_{thick} = m/2
    + H\alpha: \gamma_{thin} - \gamma_{thick} = 0.08 +/- 0.04
    + [N II]: \gamma_{thin} - \gamma_{thick} = 0.18 \pm 0.04
    + [S II]: \gamma_{thin} - \gamma_{thick} = 0.18 \pm 0.04
    + Should all be compared with m/2 = 0.1 \pm 0.05

 
* Why projection smoothing may not happen
- Projection smoothing makes the 2D structure (or autocorrelation) function steeper than the 3D one by 1.
- It will only happen for transverse scales smaller than the line-of-sight depth of the emitting layer
  + If there were a unique scale for the line-of-sight depth of the emitting layer, then there should be a break in the structure function at that scale
  + But since there will be a distribution of LOS depths, we will instead see a curvature of the structure function
    + We could measure the LOS depths - maybe for the observational paper
    + For instance z = \int \eta dz / \eta_max - although this would be a lower limit on the real effective depth
- But there is also the Brunt & Mac Low (2004) effect, where density fluctuations have an effect on the velocity centroids that can fully or partially cancel out the projection smoothing
*** Shapes of the structure functions
+ For all but the "champagne flow" case, the structure functions have negative curvature over the "power law" range
  + That is \partial{}^{2}S_2/\partial{}l^2 < 0
  + This might be hint of passing from thick to thin regime, see above
+ For looking down the z-axis, where we see a champagne flow, the structure functions have a curvature in the opposite direction
  

* Slopes of VCA power spectra

** Checking what bin width we should use
+ [X] Jane is going to save the velocity channels for me
+ I suspect that the flat slopes for the thinnest channels are due to noise
+ Turns out that channels of 5 km/s are fine
*** Velocity widths
All the n=128 PPV cubes have 1.2667 km/s channels

|   n |    dV |
|-----+-------|
| 128 |   1.3 |
|  64 |   2.5 |
|  32 |   5.1 |
|  16 |  10.1 |
|   8 |  20.3 |
|   4 |  40.5 |
|   2 |  81.1 |
|   1 | 162.1 |
#+TBLFM: $2=1.2667 (128/$1) ; f1
*** Make figure of velocity slices
#+BEGIN_SRC python :results file
  import matplotlib
  matplotlib.use('Agg')
  import aplpy
  import matplotlib.pyplot as plt
  fig = plt.figure(figsize=(8, 4))
  f1 = aplpy.FITSFigure("bigdata/y-O35007-032.fits",
                        figure=fig, subplot=[0.5,0.0,0.5,1.0],
                        slices=[13])
  f1.tick_labels.hide()
  f1.axis_labels.hide()
  f1.frame.set_linewidth(0)
  f1.show_grayscale(vmin=0.0, vmax=1.5e6, invert=True)
  
  f2 = aplpy.FITSFigure("bigdata/y-O35007-001.fits",
                        figure=fig, subplot=[0.0,0.0,0.5,1.0],
                        )
  f2.tick_labels.hide()
  f2.axis_labels.hide()
  f2.frame.set_linewidth(0)
  f2.add_scalebar(128)
  f2.scalebar.set_label("1.0 pc")
  f2.show_grayscale(vmin=0.0, vmax=4.5e6, invert=True)
  
  fig.text(0.05, 0.9, "Thick slice")
  fig.text(0.55, 0.9, "Thin slice")
  figfile = "o3-thick-thin.pdf"
  fig.savefig(figfile)
  return figfile
#+END_SRC

#+RESULTS:
[[file:o3-thick-thin.pdf]]

*** Halve resolution of PPV cube
#+BEGIN_SRC python :results output
  import numpy as np
  from astropy.io import fits
  
  def double_down(ppv):
      nv, ny, nx = ppv.shape
      return np.reshape(ppv, (nv/2, 2, ny, nx)).sum(axis=1)

  PREFIX = "04052012_4_0030-cube"
  def all_the_way(suffix):
      hdu, = fits.open("bigdata/{}-{}.fits".format(PREFIX, suffix))
      while hdu.data.shape[0] > 1:
          hdu.data = double_down(hdu.data)
          hdu.writeto("bigdata/{}-{:03d}.fits".format(suffix, hdu.data.shape[0]), clobber=True)

  cubes = ["y-Halpha", "n-Halpha", "y-O35007", "n-O35007", 
           "y-N26584", "n-N26584", "y-S26716", "n-S26716", ]
  for cube in cubes:
      all_the_way(cube)
#+END_SRC

#+RESULTS:
#+begin_example
WARNING: Overwriting existing file 'bigdata/y-Halpha-064.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/y-Halpha-032.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/y-Halpha-016.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/y-Halpha-008.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/y-Halpha-004.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/y-Halpha-002.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/y-Halpha-001.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/n-Halpha-064.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/n-Halpha-032.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/n-Halpha-016.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/n-Halpha-008.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/n-Halpha-004.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/n-Halpha-002.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/n-Halpha-001.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/y-O35007-064.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/y-O35007-032.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/y-O35007-016.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/y-O35007-008.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/y-O35007-004.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/y-O35007-002.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/y-O35007-001.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/n-O35007-064.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/n-O35007-032.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/n-O35007-016.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/n-O35007-008.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/n-O35007-004.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/n-O35007-002.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/n-O35007-001.fits'. [astropy.io.fits.hdu.hdulist]
#+end_example

** Problems with the thick velocity slices

+ 
** From Esquivel, Lazarian, Pogosyan, & Cho (2003)
+ n is 3D density spectral index (negative)
  + We have \kappa = n + 2, but we also use m for same thing
  + In our case, it is the emissivity rather than density that is relevant
  + Simulations:
    + \kappa(d_i) \simeq -1.2
    + \kappa(d_i^2) = \kappa(H\alpha) \simeq -1.1 \to -0.8 \to -0.9
    + \kappa([O III]) \simeq -1.5 \to -1.3
  + The shallow/steep boundary is at -1 in our units, so we are hovering around the boundary, with [O III] steep and H\alpha shallow
+ \mu is 3D velocity spectral index (negative)
  + Simulations have \kappa(v_i) \simeq -1.3 \to -1.1 \to -1.2 
+ \gamma is spectral index in velocity slices (negative)
+ m is structure function index of the velocity (positive)
  + We use 2\gamma for the same quantity, but then use m in the table
    + This comes from \Delta{}v_rms \sim L^\gamma
    + Kolmogorov,Burger predict \gamma = 1/3,1/2 => m_{3D} = 2/3,1
  + But this is 3D, not 2D.  Does it make a difference?
    + *Maybe*
      + Projection smoothing gives m_{2D} = m_{3D} + 1
      + But we can have m_{2D} = m_{3D} in certain cases:
        1. If line-of-sight depth of emitting region is smaller than separation scale
           - this should certainly be the case for the [N II] and [S II] lines
        2. In driven turbulence, correlations \Delta\rho-\Delta{}v can undo the projection smoothing (Brunt & Mac Low 2004)
      + In general we can put  m_{2D} = m_{3D} + \delta_{smooth}, where \delta_{smooth} = [0 \dots 1] 
    + Simulation measurements have
      + m_{2D}([S II]) = 0.45 \pm 0.01
      + m_{2D}([N II]) = 0.55 \pm 0.02
      + m_{2D}(H\alpha) = 0.60 \pm 0.03
      + m_{2D}([O III]) = 0.75 \pm 0.03
        + Except for xy plane where it reaches 1.0
    + *If we believe projection smoothing* => m_{3D} \approx -0.45 (H\alpha) or -0.3 ([O III])
      + If we don't, then it could be anywhere in the range m_{3D} \approx -0.45 \rightarrow 0.55
    + Prediction from velocity power spectrum is
      + m = -3 - \mu = -1 - \kappa(v_i) = 0.3 \to 0.1 \to 0.2
    + Average m = 0.2 \pm 0.1, so we can see that \delta_{smooth} varies from 0.25 for [S II] up to 0.55 for [O III]
      + It increases as the emitting region geometry transitions from sheet-like to diffuse
      + It is not zero even for [S II], presumably because there is /some/ diffuse emission, and/or we sometimes

\alpha\beta\gamma\delta\epsilon\zeta\eta\theta\iota\kappa\lambda\mu\nu\omicron\pi\varpi\rho\sigma\tau\upsilon\xi\chi\omega \Alpha\Beta\Gamma\Delta\Epsilon\Zeta\Eta\Theta\Iota\Kappa\Lambda\Mu\Nu\Omicron\Pi\Rho\Sigma\sum\Tau\Upsilon\Xi\Chi\Omega


*** Table of structure function indices
| Time        | 150,000 |      |      | 200,000 |      |      | 250,000 |      |      | 300,000 |      |      |               |
| Plane       |     x−y |  x−z |  y−z |     x−y |  x−z |  y−z |     x−y |  x−z |  y−z |     x−y |  x−z |  y−z | AVERAGE       |
|-------------+---------+------+------+---------+------+------+---------+------+------+---------+------+------+---------------|
| Hα          |    0.51 | 0.60 | 0.67 |    0.61 | 0.51 | 0.60 |    0.71 | 0.53 | 0.51 |    0.79 | 0.58 | 0.61 | 0.60 +/- 0.03 |
| [OIII]λ5007 |    0.69 | 0.77 | 0.87 |    0.68 | 0.78 | 0.70 |    0.83 | 0.73 | 0.59 |    1.02 | 0.63 | 0.74 | 0.75 +/- 0.03 |
| [NII]λ6584  |    0.46 | 0.54 | 0.58 |    0.54 | 0.44 | 0.56 |    0.60 | 0.48 | 0.55 |    0.66 | 0.63 | 0.53 | 0.55 +/- 0.02 |
| [SII]λ6716  |    0.41 | 0.44 | 0.50 |    0.44 | 0.37 | 0.47 |    0.45 | 0.43 | 0.48 |    0.43 | 0.47 | 0.48 | 0.45 +/- 0.01 |
#+TBLFM: $14=vmeane($2..$13); f2


Same, but without the 150,000 years 
| Time        | 200,000 |      |      | 250,000 |      |      | 300,000 |      |      |               |
| Plane       |     x−y |  x−z |  y−z |     x−y |  x−z |  y−z |     x−y |  x−z |  y−z | AVERAGE       |
|-------------+---------+------+------+---------+------+------+---------+------+------+---------------|
| Hα          |    0.61 | 0.51 | 0.60 |    0.71 | 0.53 | 0.51 |    0.79 | 0.58 | 0.61 | 0.61 +/- 0.03 |
| [OIII]λ5007 |    0.68 | 0.78 | 0.70 |    0.83 | 0.73 | 0.59 |    1.02 | 0.63 | 0.74 | 0.74 +/- 0.04 |
| [NII]λ6584  |    0.54 | 0.44 | 0.56 |    0.60 | 0.48 | 0.55 |    0.66 | 0.63 | 0.53 | 0.55 +/- 0.02 |
| [SII]λ6716  |    0.44 | 0.37 | 0.47 |    0.45 | 0.43 | 0.48 |    0.43 | 0.47 | 0.48 | 0.45 +/- 0.01 |
#+TBLFM: $11=vmeane($2..$10); f2




*** Relation between velocity energy spectrum \mu and structure function m
+ In three dimensions: \mu = -3 - m
+ From simulations: m = -0.45 \rightarrow 0.55 => \mu = -2.55 \rightarrow -3.55
+ Whereas really the simulations have \mu = -3.2 \pm 0.1

*** Relation between m and VCA slope \gamma
**** Shallow density spectrum:
+ \gamma_{thin} = n + m/2
+ \gamma_{thick} = n
**** Steep density spectrum:
+ \gamma_{thin} = -3 + m/2
+ \gamma_{thick} = -3 - m/2
+ \gamma_{THICK} = n  (THICK means basically the whole line)
**** Our simulations
+ We have \mu = -3.2 \pm 0.1, m = 0.2 \pm 0.1, n([O III]) = -3.4 \pm 0.1, n(H\alpha) = -2.95 \pm 0.15
***** Predicted [O III] steep
+ \gamma_{thin} = -2.9 \pm 0.1 - observed: -2.84 \pm 0.11 (x-axis)
+ \gamma_{thick} = -3.2 \pm 0.1 - NOT OBSERVED
  + But this is just the thinnest case with thermal broadening; we don't actually know it corresponds to the "thick" case
+ \gamma_{THICK}_{} = -3.4 \pm 0.1 - observed: -3.38 \pm 0.04
+ So this works well
***** Predicted H\alpha shallow
+ \gamma_{thin} = -2.85 \pm 0.15 - observed -2.5 
+ \gamma_{thick} = -2.95 \pm 0.15 - observed -2.59 \pm 0.02 
+ So the difference between them is 0.1, which is what is expected
+ But the absolute value of the thick index is too shallow
**** Deduction of m from VCA slopes

***** Shallow, applied to H\alpha
+ => m = 2 (\gamma_{thin} - \gamma_{thick})
+ This gives 0.66 \pm 0.03 with no broadening, which is too steep
+ With broadening it gives 0.24 \pm 0.08, which is the right answer!
  + But it must be a coincidence

***** Steep, applied to [O III]
****** Just thin
+ m = 2 (3 + \gamma_{thin})
+ From "observed" \gamma_{thin} = -2.06 \pm 0.03 => m = 1.88 +/- 0.06
  + This is far too steep => \mu = -4.9
+ With thermal broadening, the observed \gamma_{thin} = -2.67 \pm 0.04 => m = 0.66 +/- 0.08
  + Still too large (\mu = -3.7), but more reasonable
****** Old useless stuff
******* Thin \to medium thick
+ => m = (\gamma_{thin} - \gamma_{thick})
******* Medium thick \to very thick
+ AND \gamma_{thick} - \gamma_{THICK} = -3 - n - m/2
+ => m = 2 [-(n + 3) - (\gamma_{thick} - \gamma_{THICK})]
+ OR \gamma_{thin} - \gamma_{THICK} = -3 - n + m/2
+ => m = 2 [ (n + 3) + (\gamma_{thin} - \gamma_{THICK}) ]
******* Application to [O III]
+ For [O III], n = -3.4 \pm 0.1 => n + 3 = -0.4 \pm 0.1
+ => m_thin = 2 [-0.4 \pm 0.1  + (\gamma_{thin} - \gamma_{THICK})]
+ OR m_med = 2 [0.4 \pm 0.1 - (\gamma_{thick} - \gamma_{THICK})]
+ In the table below we take "Diff NB" = (\gamma_{thin} - \gamma_{THICK})
+ We also try assuming "Diff B" = (\gamma_{thick} - \gamma_{THICK}), *although this is less certain*

** Simulation [O III] slopes

| Time |          Thick |        Thin NB |         Thin B |
|------+----------------+----------------+----------------|
|   15 |          -3.47 |          -2.89 |          -3.13 |
|   20 |          -3.29 |          -2.63 |          -2.85 |
|   25 |          -3.40 |          -2.52 |          -2.74 |
|   30 |          -3.37 |          -2.41 |          -2.64 |
|------+----------------+----------------+----------------|
|   15 |          -3.14 |          -2.73 |          -3.01 |
|   20 |          -3.18 |          -2.55 |          -2.76 |
|   25 |          -3.31 |          -2.48 |          -2.69 |
|   30 |          -3.39 |          -2.46 |          -2.68 |
|------+----------------+----------------+----------------|
|   15 |          -3.42 |          -2.51 |          -2.71 |
|   20 |          -3.26 |          -2.51 |          -2.69 |
|   25 |          -3.34 |          -2.45 |          -2.69 |
|   30 |          -3.43 |          -2.58 |          -2.79 |
|------+----------------+----------------+----------------|
|      | -3.33 +/- 0.03 | -2.56 +/- 0.04 | -2.78 +/- 0.04 |
#+TBLFM: @14$2..@14$4=vmeane(@I..@IIII);f2


** Simulation [N II] slopes

| Time |          Thick |        Thin NB |         Thin B |  Thin - Thick |
|------+----------------+----------------+----------------+---------------|
|   15 |          -2.41 |          -2.13 |          -2.28 |          0.13 |
|   20 |          -2.61 |          -2.18 |          -2.36 |          0.25 |
|   25 |          -2.42 |          -2.13 |          -2.28 |          0.14 |
|   30 |          -2.58 |          -2.20 |          -2.35 |          0.23 |
|------+----------------+----------------+----------------+---------------|
|   15 |          -2.38 |          -2.05 |          -2.20 |          0.18 |
|   20 |          -2.48 |          -2.17 |          -2.31 |          0.17 |
|   25 |          -2.61 |          -2.22 |          -2.39 |          0.22 |
|   30 |          -2.52 |          -2.17 |          -2.33 |          0.19 |
|------+----------------+----------------+----------------+---------------|
|   15 |          -2.42 |          -2.16 |          -2.30 |          0.12 |
|   20 |          -2.44 |          -2.14 |          -2.29 |          0.15 |
|   25 |          -2.63 |          -2.22 |          -2.38 |          0.25 |
|   30 |          -2.66 |          -2.28 |          -2.45 |          0.21 |
|------+----------------+----------------+----------------+---------------|
|      | -2.51 +/- 0.03 | -2.17 +/- 0.02 | -2.33 +/- 0.02 | 0.18 +/- 0.04 |
#+TBLFM: $5=$4 - $2;f2::@14$2..@14$4=vmeane(@I..@IIII);f2

** Simulation [S II] slopes
| Time |          Thick |        Thin NB |         Thin B |  Thin - Thick |
|------+----------------+----------------+----------------+---------------|
|   15 |          -2.13 |          -1.76 |          -1.87 |          0.26 |
|   20 |          -2.03 |          -1.82 |          -1.89 |          0.14 |
|   25 |          -1.84 |          -1.69 |          -1.76 |          0.08 |
|   30 |          -1.85 |          -1.59 |          -1.66 |          0.19 |
|------+----------------+----------------+----------------+---------------|
|   15 |          -1.96 |          -1.61 |          -1.69 |          0.27 |
|   20 |          -1.82 |          -1.69 |          -1.74 |          0.08 |
|   25 |          -2.19 |          -1.96 |          -2.02 |          0.17 |
|   30 |          -1.92 |          -1.64 |          -1.71 |          0.21 |
|------+----------------+----------------+----------------+---------------|
|   15 |          -2.11 |          -1.90 |          -1.96 |          0.15 |
|   20 |          -2.04 |          -1.75 |          -1.86 |          0.18 |
|   25 |          -1.97 |          -1.76 |          -1.80 |          0.17 |
|   30 |          -1.96 |          -1.73 |          -1.78 |          0.18 |
|------+----------------+----------------+----------------+---------------|
|      | -1.99 +/- 0.03 | -1.74 +/- 0.03 | -1.81 +/- 0.03 | 0.18 +/- 0.04 |
#+TBLFM: $5=$4 - $2;f2::@14$2..@14$4=vmeane(@I..@IIII);f2



** Simulation H\alpha slopes

| Time |          Thick |        Thin NB |         Thin B |  Thin - Thick |
|------+----------------+----------------+----------------+---------------|
|   15 |          -2.65 |          -2.54 |          -2.67 |         -0.02 |
|   20 |          -2.63 |          -2.41 |          -2.58 |          0.05 |
|   25 |          -2.61 |          -2.31 |          -2.48 |          0.13 |
|   30 |          -2.56 |          -2.23 |          -2.37 |          0.19 |
|------+----------------+----------------+----------------+---------------|
|   15 |          -2.52 |          -2.49 |          -2.63 |         -0.11 |
|   20 |          -2.55 |          -2.35 |          -2.51 |          0.04 |
|   25 |          -2.60 |          -2.29 |          -2.45 |          0.15 |
|   30 |          -2.53 |          -2.23 |          -2.39 |          0.14 |
|------+----------------+----------------+----------------+---------------|
|   15 |          -2.66 |          -2.40 |          -2.64 |          0.02 |
|   20 |          -2.49 |          -2.26 |          -2.42 |          0.07 |
|   25 |          -2.62 |          -2.29 |          -2.50 |          0.12 |
|   30 |          -2.66 |          -2.35 |          -2.48 |          0.18 |
|------+----------------+----------------+----------------+---------------|
|      | -2.59 +/- 0.02 | -2.35 +/- 0.03 | -2.51 +/- 0.03 | 0.08 +/- 0.04 |
#+TBLFM: $5=$4 - $2;f2::@14$2..@14$4=vmeane(@I..@IIII);f2

** Original data tables from Jane                                  :noexport:



*** New vca-11-tab.dat - z-axis
:LOGBOOK:
- Note taken on [2013-12-13 Fri 08:45] \\
  Updated
:END:
          Thick            Thin

Halpha
No broadening
15        -2.65           -2.54		
20        -2.63           -2.41
25        -2.61           -2.31
30        -2.56           -2.23
Broadening
15        -2.65           -2.67
20        -2.63           -2.58
25        -2.61           -2.48
30        -2.56           -2.37

O35007
No broadening
15        -3.58           -2.90
20        -3.32           -2.62
25        -3.37           -2.57
30        -3.38           -2.46
Broadening
15        -3.58           -3.15
20        -3.32           -2.84
25        -3.37           -2.78
30        -3.38           -2.69

N26584
No broadening
15        -2.41           -2.13
20        -2.61           -2.18
25        -2.42           -2.13
30        -2.58           -2.20
Broadening
15        -2.41           -2.28
20        -2.61           -2.36
25        -2.42           -2.28
30        -2.58           -2.35

S26716
No broadening
15        -2.13           -1.76
20        -2.03           -1.82
25        -1.84           -1.69
30        -1.85           -1.59
Broadening
15        -2.13           -1.87
20        -2.03           -1.89
25        -1.84           -1.76
30        -1.85           -1.66

*** New vca-21-tab.dat - y-axis
          Thick            Thin

Halpha
No broadening
15        -2.52           -2.49                    		
20        -2.55           -2.35
25        -2.60           -2.29
30        -2.53           -2.23
Broadening
15        -2.52           -2.63
20        -2.55           -2.51
25        -2.60           -2.45
30        -2.53           -2.39

O35007
No broadening
15        -3.14           -2.73        
20        -3.18           -2.55
25        -3.31           -2.48
30        -3.39           -2.46
Broadening
15        -3.14           -3.01
20        -3.18           -2.76
25        -3.31           -2.69
30        -3.39           -2.68

N26584
No broadening
15        -2.38           -2.05
20        -2.48           -2.17
25        -2.61           -2.22
30        -2.52           -2.17
Broadening
15        -2.38           -2.20
20        -2.48           -2.31
25        -2.61           -2.39
30        -2.52           -2.33

S26716
No broadening
15        -1.96           -1.61
20        -1.82           -1.69
25        -2.19           -1.96
30        -1.92           -1.64
Broadening
15        -1.96           -1.69
20        -1.82           -1.74
25        -2.19           -2.02
30        -1.92           -1.71



*** New vca-31-tab.dat - x-axis
          Thick            Thin

Halpha
No broadening
15        -2.66           -2.40                            		
20        -2.49           -2.26
25        -2.62           -2.29
30        -2.66           -2.35
Broadening
15        -2.66           -2.64
20        -2.49           -2.42
25        -2.62           -2.50
30        -2.66           -2.48

O35007
No broadening
15        -3.42           -2.51        
20        -3.26           -2.51
25        -3.34           -2.45
30        -3.43           -2.58
Broadening
15        -3.42           -2.71
20        -3.26           -2.69
25        -3.34           -2.69
30        -3.43           -2.79

N26584
No broadening
15        -2.42           -2.16
20        -2.44           -2.14
25        -2.63           -2.22
30        -2.66           -2.28
Broadening
15        -2.42           -2.30
20        -2.44           -2.29
25        -2.63           -2.38
30        -2.66           -2.45

S26716
No broadening
15        -2.11           -1.90
20        -2.04           -1.75
25        -1.97           -1.76
30        -1.96           -1.73
Broadening
15        -2.11           -1.96
20        -2.04           -1.86
25        -1.97           -1.80
30        -1.96           -1.78


