Stuff for the Sac and Jane paper on turbulence diagnostics


* Conclusions
** Intrinsic power spectra of physical quantities
+ We have good power laws over a reasonable range
+ Ionized gas velocity has slope \mu = -3.2 \pm 0.1 once the turbulence is fully developed
  + This rather shallow compared with Kolmogorov (\mu = -3.667) or Burgers (\mu = -4.0), implying relatively more velocity structure at smaller scales than is seen in an inertial cascade
  + One reason for this may be the injection of energy at all scales
  + The associated autocorrelation slope of u^2 (or second-order structure function slope) is m = -3 - \mu = 0.2 \pm 0.1, where \delta{}u \sim L^{m/2}
  + So u \sim L^{0.1 \pm 0.05}, which is remarkably shallow.  It means that with \sigma \approx 10 km/s on scale of 1 pc, we will still have \sigma = 8 km/s on scale of 0.1 pc
+ Density has slope n = -3.2, same as velocity, but more relevant are emissivity slopes: n = -2.9 \pm 0.1 for H\alpha and n = -3.4 \pm 0.1 for [O III]
** We want to see if we can diagnose the intrinsic power spectrum from observables
+ In particular the power law index of the ionized gas velocity power spectrum, which is -3.2 \pm 0.1 in our simulations
+ Can it be deduced from the /Structure Function/ or the /Velocity Channel Analysis/?
*** Structure function
+ has big advantage that it is relatively immune to effects of thermal broadening and poor instrumental resolution, so can be used for H\alpha
+ big disadvantage that it has the uncertainty of projection smoothing
  + smoothing should apply at scales smaller than the characteristic line-of-sight depth of the emitting gas
  + would give a break of magnitude \delta{}m = 1 in the spectrum (steeper at smaller scales, where the smoothing operates)
  + except that the line-of-sight depth has a distribution, rather than a fixed value, since it varies from point to point, so that instead of a break, we should see a negative curvature to the structure function over the fitted range
  + Just such curvature is seen (mostly)
  + In addition, we see a clear progression from [S II] \to [N II] \to H\alpha \to [O III]
    + m_{2D}([S II]) = 0.45 \pm 0.01
    + m_{2D}([N II]) = 0.55 \pm 0.02
    + m_{2D}(H\alpha) = 0.60 \pm 0.03
    + m_{2D}([O III]) = 0.75 \pm 0.03
  + Based on the simulation's velocity power spectrum index of \mu \approx -3.2, this should have a value between:
    + m_{2D} = 0.2 (no smoothing), and
    + m_{2D} = 1.2 (full smoothing)
  + The results are obviously consistent with this, and seem to follow a consistent trend with less smoothing (shallower spectrum) where the emission is more sheet-like ([S II]), progressing to more smoothing where the emission is more diffuse ([O III])
  + But nothing is clearly in any particular limit, so it is impossible to infer \mu from the observations
  + PLUS added complication of the Brunt & Mac Low (2004) effect, where density (emissivity) fluctuations correlated with the velocity fluctuations can effect the velocity centroid distributions and partially or fully cancel out the projection smoothing effect
  + PLUS AGAIN it is affected by champagne flows along line of sight, which steepen the structure function without any concommitant change in \mu
    + This happens mainly at the larger separations in the fitting range, which gives it a positive curvature, allowing it to be potentially spotted.  Another telltale sign is a shoulder on the velocity PDF
*** VCA
+ We use 5 km/s slices as the thin limit
  + This is the highest resolution that can regularly be achieved with current echelle spectrographs
  + Also, thermal broadening means that most lines would not benefit from going to higher resolution
  + And smaller slices also run into problems with discretization noise in the simulations that produces spurious small-scale power, as discussed by Esquivel
+ The thick slices should have an index \gamma_{thick} equal to the power law index n of the 3D power spectrum of the line emissivity in all cases (/but are we really sure of this/):
  + [O III]: \gamma_{thick} = -3.38 \pm 0.04, n = -3.4 \pm 0.1 /YES/
  + H\alpha:  \gamma_{thick} = -2.59 \pm 0.02, n = -2.95 \pm 0.15 /PCA thick slope is too shallow!/
  + [N II]:
  + [S II]: 
+ The thin slices, with width < \delta{}v(k), should have a shallower slope \gamma_{thin}, which depends on the velocity fluctuations \mu, or equivalently m = 3 - \mu
+ There are two cases:
  + steep emissivity, n < -3, appropriate to [O III]: \gamma_{thin} = -3 + m/2
    + [O III]: \gamma_{thin} = -2.84 \pm 0.11 (x-axis), -3 + m/2 = -2.9 /YES/
  + shallow emissivity, n > -3, appropriate to the other lines:  \gamma_{thin} - \gamma_{thick} = m/2
    + H\alpha: 
    + [N II]:
    + [S II]:

 
* Why projection smoothing may not happen
- Projection smoothing makes the 2D structure (or autocorrelation) function steeper than the 3D one by 1.
- It will only happen for transverse scales smaller than the line-of-sight depth of the emitting layer
  + If there were a unique scale for the line-of-sight depth of the emitting layer, then there should be a break in the structure function at that scale
  + But since there will be a distribution of LOS depths, we will instead see a curvature of the structure function
    + We could measure the LOS depths - maybe for the observational paper
    + For instance z = \int \eta dz / \eta_max - although this would be a lower limit on the real effective depth
- But there is also the Brunt & Mac Low (2004) effect, where density fluctuations have an effect on the velocity centroids that can fully or partially cancel out the projection smoothing
*** Shapes of the structure functions
+ For all but the "champagne flow" case, the structure functions have negative curvature over the "power law" range
  + That is \partial{}^{2}S_2/\partial{}l^2 < 0
  + This might be hint of passing from thick to thin regime, see above
+ For looking down the z-axis, where we see a champagne flow, the structure functions have a curvature in the opposite direction
  

* Slopes of VCA power spectra

** Checking what bin width we should use
+ [X] Jane is going to save the velocity channels for me
+ I suspect that the flat slopes for the thinnest channels are due to noise
+ Turns out that channels of 5 km/s are fine
*** Velocity widths
All the n=128 PPV cubes have 1.2667 km/s channels

|   n |    dV |
|-----+-------|
| 128 |   1.3 |
|  64 |   2.5 |
|  32 |   5.1 |
|  16 |  10.1 |
|   8 |  20.3 |
|   4 |  40.5 |
|   2 |  81.1 |
|   1 | 162.1 |
#+TBLFM: $2=1.2667 (128/$1) ; f1
*** Make figure of velocity slices
#+BEGIN_SRC python :results file
from astropy.io import fits

return figfile
#+END_SRC
*** Halve resolution of PPV cube
#+BEGIN_SRC python :results output
  import numpy as np
  from astropy.io import fits
  
  def double_down(ppv):
      nv, ny, nx = ppv.shape
      return np.reshape(ppv, (nv/2, 2, ny, nx)).sum(axis=1)

  PREFIX = "04052012_4_0030-cube"
  def all_the_way(suffix):
      hdu, = fits.open("bigdata/{}-{}.fits".format(PREFIX, suffix))
      while hdu.data.shape[0] > 1:
          hdu.data = double_down(hdu.data)
          hdu.writeto("bigdata/{}-{:03d}.fits".format(suffix, hdu.data.shape[0]), clobber=True)

  cubes = ["y-Halpha", "n-Halpha", "y-O35007", "n-O35007"]
  for cube in cubes:
      all_the_way(cube)
#+END_SRC

#+RESULTS:
#+begin_example
WARNING: Overwriting existing file 'bigdata/y-Halpha-064.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/y-Halpha-032.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/y-Halpha-016.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/y-Halpha-008.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/y-Halpha-004.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/y-Halpha-002.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/y-Halpha-001.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/n-Halpha-064.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/n-Halpha-032.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/n-Halpha-016.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/n-Halpha-008.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/n-Halpha-004.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/n-Halpha-002.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/n-Halpha-001.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/y-O35007-064.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/y-O35007-032.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/y-O35007-016.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/y-O35007-008.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/y-O35007-004.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/y-O35007-002.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/y-O35007-001.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/n-O35007-064.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/n-O35007-032.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/n-O35007-016.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/n-O35007-008.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/n-O35007-004.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/n-O35007-002.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/n-O35007-001.fits'. [astropy.io.fits.hdu.hdulist]
#+end_example

** From Esquivel, Lazarian, Pogosyan, & Cho (2003)
+ n is 3D density spectral index (negative)
  + We have \kappa = n + 2, but we also use m for same thing
  + In our case, it is the emissivity rather than density that is relevant
  + Simulations:
    + \kappa(d_i) \simeq -1.2
    + \kappa(d_i^2) = \kappa(H\alpha) \simeq -1.1 \to -0.8 \to -0.9
    + \kappa([O III]) \simeq -1.5 \to -1.3
  + The shallow/steep boundary is at -1 in our units, so we are hovering around the boundary, with [O III] steep and H\alpha shallow
+ \mu is 3D velocity spectral index (negative)
  + Simulations have \kappa(v_i) \simeq -1.3 \to -1.1 \to -1.2 
+ \gamma is spectral index in velocity slices (negative)
+ m is structure function index of the velocity (positive)
  + We use 2\gamma for the same quantity, but then use m in the table
    + This comes from \Delta{}v_rms \sim L^\gamma
    + Kolmogorov,Burger predict \gamma = 1/3,1/2 => m_{3D} = 2/3,1
  + But this is 3D, not 2D.  Does it make a difference?
    + *Maybe*
      + Projection smoothing gives m_{2D} = m_{3D} + 1
      + But we can have m_{2D} = m_{3D} in certain cases:
        1. If line-of-sight depth of emitting region is smaller than separation scale
           - this should certainly be the case for the [N II] and [S II] lines
        2. In driven turbulence, correlations \Delta\rho-\Delta{}v can undo the projection smoothing (Brunt & Mac Low 2004)
      + In general we can put  m_{2D} = m_{3D} + \delta_{smooth}, where \delta_{smooth} = [0 \dots 1] 
    + Simulation measurements have
      + m_{2D}([S II]) = 0.45 \pm 0.01
      + m_{2D}([N II]) = 0.55 \pm 0.02
      + m_{2D}(H\alpha) = 0.60 \pm 0.03
      + m_{2D}([O III]) = 0.75 \pm 0.03
        + Except for xy plane where it reaches 1.0
    + *If we believe projection smoothing* => m_{3D} \approx -0.45 (H\alpha) or -0.3 ([O III])
      + If we don't, then it could be anywhere in the range m_{3D} \approx -0.45 \rightarrow 0.55
    + Prediction from velocity power spectrum is
      + m = -3 - \mu = -1 - \kappa(v_i) = 0.3 \to 0.1 \to 0.2
    + Average m = 0.2 \pm 0.1, so we can see that \delta_{smooth} varies from 0.25 for [S II] up to 0.55 for [O III]
      + It increases as the emitting region geometry transitions from sheet-like to diffuse
      + It is not zero even for [S II], presumably because there is /some/ diffuse emission, and/or we sometimes

\alpha\beta\gamma\delta\epsilon\zeta\eta\theta\iota\kappa\lambda\mu\nu\omicron\pi\varpi\rho\sigma\tau\upsilon\xi\chi\omega \Alpha\Beta\Gamma\Delta\Epsilon\Zeta\Eta\Theta\Iota\Kappa\Lambda\Mu\Nu\Omicron\Pi\Rho\Sigma\sum\Tau\Upsilon\Xi\Chi\Omega


*** Table of structure function indices
| Time        | 150,000 |      |      | 200,000 |      |      | 250,000 |      |      | 300,000 |      |      |               |
| Plane       |     x−y |  x−z |  y−z |     x−y |  x−z |  y−z |     x−y |  x−z |  y−z |     x−y |  x−z |  y−z | AVERAGE       |
|-------------+---------+------+------+---------+------+------+---------+------+------+---------+------+------+---------------|
| Hα          |    0.51 | 0.60 | 0.67 |    0.61 | 0.51 | 0.60 |    0.71 | 0.53 | 0.51 |    0.79 | 0.58 | 0.61 | 0.60 +/- 0.03 |
| [OIII]λ5007 |    0.69 | 0.77 | 0.87 |    0.68 | 0.78 | 0.70 |    0.83 | 0.73 | 0.59 |    1.02 | 0.63 | 0.74 | 0.75 +/- 0.03 |
| [NII]λ6584  |    0.46 | 0.54 | 0.58 |    0.54 | 0.44 | 0.56 |    0.60 | 0.48 | 0.55 |    0.66 | 0.63 | 0.53 | 0.55 +/- 0.02 |
| [SII]λ6716  |    0.41 | 0.44 | 0.50 |    0.44 | 0.37 | 0.47 |    0.45 | 0.43 | 0.48 |    0.43 | 0.47 | 0.48 | 0.45 +/- 0.01 |
#+TBLFM: $14=vmeane($2..$13); f2



*** Relation between velocity energy spectrum \mu and structure function m
+ In three dimensions: \mu = -3 - m
+ From simulations: m = -0.45 \rightarrow 0.55 => \mu = -2.55 \rightarrow -3.55
+ Whereas really the simulations have \mu = -3.2 \pm 0.1

*** Relation between m and VCA slope \gamma
**** Shallow density spectrum:
+ \gamma_{thin} = n + m/2
+ \gamma_{thick} = n
**** Steep density spectrum:
+ \gamma_{thin} = -3 + m/2
+ \gamma_{thick} = -3 - m/2
+ \gamma_{THICK} = n  (THICK means basically the whole line)
**** Our simulations
+ We have \mu = -3.2 \pm 0.1, m = 0.2 \pm 0.1, n([O III]) = -3.4 \pm 0.1, n(H\alpha) = -2.95 \pm 0.15
***** Predicted [O III] steep
+ \gamma_{thin} = -2.9 \pm 0.1 - observed: -2.84 \pm 0.11 (x-axis)
+ \gamma_{thick} = -3.2 \pm 0.1 - NOT OBSERVED
  + But this is just the thinnest case with thermal broadening; we don't actually know it corresponds to the "thick" case
+ \gamma_{THICK}_{} = -3.4 \pm 0.1 - observed: -3.38 \pm 0.04
+ So this works well
***** Predicted H\alpha shallow
+ \gamma_{thin} = -2.85 \pm 0.15 - observed -2.5 
+ \gamma_{thick} = -2.95 \pm 0.15 - observed -2.59 \pm 0.02 
+ So the difference between them is 0.1, which is what is expected
+ But the absolute value of the thick index is too shallow
**** Deduction of m from VCA slopes

***** Shallow, applied to H\alpha
+ => m = 2 (\gamma_{thin} - \gamma_{thick})
+ This gives 0.66 \pm 0.03 with no broadening, which is too steep
+ With broadening it gives 0.24 \pm 0.08, which is the right answer!
  + But it must be a coincidence

***** Steep, applied to [O III]
****** Just thin
+ m = 2 (3 + \gamma_{thin})
+ From "observed" \gamma_{thin} = -2.06 \pm 0.03 => m = 1.88 +/- 0.06
  + This is far too steep => \mu = -4.9
+ With thermal broadening, the observed \gamma_{thin} = -2.67 \pm 0.04 => m = 0.66 +/- 0.08
  + Still too large (\mu = -3.7), but more reasonable
****** Old useless stuff
******* Thin \to medium thick
+ => m = (\gamma_{thin} - \gamma_{thick})
******* Medium thick \to very thick
+ AND \gamma_{thick} - \gamma_{THICK} = -3 - n - m/2
+ => m = 2 [-(n + 3) - (\gamma_{thick} - \gamma_{THICK})]
+ OR \gamma_{thin} - \gamma_{THICK} = -3 - n + m/2
+ => m = 2 [ (n + 3) + (\gamma_{thin} - \gamma_{THICK}) ]
******* Application to [O III]
+ For [O III], n = -3.4 \pm 0.1 => n + 3 = -0.4 \pm 0.1
+ => m_thin = 2 [-0.4 \pm 0.1  + (\gamma_{thin} - \gamma_{THICK})]
+ OR m_med = 2 [0.4 \pm 0.1 - (\gamma_{thick} - \gamma_{THICK})]
+ In the table below we take "Diff NB" = (\gamma_{thin} - \gamma_{THICK})
+ We also try assuming "Diff B" = (\gamma_{thick} - \gamma_{THICK}), *although this is less certain*

** Simulation [O III] slopes


*** New [O III]
| Time |          Thick |        Thin NB |         Thin B |
|------+----------------+----------------+----------------|
|   15 |          -3.47 |          -2.89 |          -3.13 |
|   20 |          -3.29 |          -2.63 |          -2.85 |
|   25 |          -3.40 |          -2.52 |          -2.74 |
|   30 |          -3.37 |          -2.41 |          -2.64 |
|------+----------------+----------------+----------------|
|      | -3.38 +/- 0.04 | -2.61 +/- 0.10 | -2.84 +/- 0.11 |
#+TBLFM: @6$2..@6$4=vmeane(@I..@II);f2
*** Old [O III]
Note that these all need 1 subtracting from them
| Time |          Thick |        Thin NB |         Thin B |         m(NB) |          m(B) |
|------+----------------+----------------+----------------+---------------+---------------|
|   15 |          -2.58 |          -1.32 |          -2.01 |          1.36 |         -0.02 |
|   20 |          -2.32 |          -1.13 |          -1.74 |          1.74 |          0.52 |
|   25 |          -2.37 |          -1.07 |          -1.66 |          1.86 |          0.68 |
|   30 |          -2.38 |          -0.98 |          -1.57 |          2.04 |          0.86 |
|------+----------------+----------------+----------------+---------------+---------------|
|   15 |          -2.14 |          -1.07 |          -1.85 |          1.86 |          0.30 |
|   20 |          -2.18 |          -1.04 |          -1.64 |          1.92 |          0.72 |
|   25 |          -2.31 |          -1.03 |          -1.59 |          1.94 |          0.82 |
|   30 |          -2.39 |          -0.97 |          -1.56 |          2.06 |          0.88 |
|------+----------------+----------------+----------------+---------------+---------------|
|   15 |          -2.42 |          -0.98 |          -1.60 |          2.04 |          0.80 |
|   20 |          -2.26 |          -1.01 |          -1.58 |          1.98 |          0.84 |
|   25 |          -2.34 |          -0.99 |          -1.59 |          2.02 |          0.82 |
|   30 |          -2.43 |          -1.10 |          -1.68 |          1.80 |          0.64 |
|------+----------------+----------------+----------------+---------------+---------------|
|      | -2.34 +/- 0.03 | -1.06 +/- 0.03 | -1.67 +/- 0.04 | 1.88 +/- 0.06 | 0.66 +/- 0.08 |
#+TBLFM: $5=2 (2 + $3);f2::$6=2 (2 + $4);f2::@14$2..@14$4=vmeane(@I..@IIII); f2


* Simulation H\alpha slopes
| Time |          Thick |        Thin NB |         Thin B | (Thin - Thick) NB | (Thin - Thick) B |         m(NB) |          m(B) |
|------+----------------+----------------+----------------+-------------------+------------------+---------------+---------------|
|   15 |          -1.65 |          -1.11 |          -1.65 |              0.54 |             0.00 |          1.08 |          0.00 |
|   20 |          -1.63 |          -1.00 |          -1.56 |              0.63 |             0.07 |          1.26 |          0.14 |
|   25 |          -1.61 |          -0.88 |          -1.42 |              0.73 |             0.19 |          1.46 |          0.38 |
|   30 |          -1.56 |          -0.85 |          -1.30 |              0.71 |             0.26 |          1.42 |          0.52 |
|------+----------------+----------------+----------------+-------------------+------------------+---------------+---------------|
|   15 |          -1.52 |          -0.96 |          -1.61 |              0.56 |            -0.09 |          1.12 |         -0.18 |
|   20 |          -1.55 |          -0.93 |          -1.48 |              0.62 |             0.07 |          1.24 |          0.14 |
|   25 |          -1.60 |          -0.92 |          -1.38 |              0.68 |             0.22 |          1.36 |          0.44 |
|   30 |          -1.53 |          -0.86 |          -1.33 |              0.67 |             0.20 |          1.34 |          0.40 |
|------+----------------+----------------+----------------+-------------------+------------------+---------------+---------------|
|   15 |          -1.66 |          -0.92 |          -1.62 |              0.74 |             0.04 |          1.48 |          0.08 |
|   20 |          -1.49 |          -0.91 |          -1.40 |              0.58 |             0.09 |          1.16 |          0.18 |
|   25 |          -1.62 |          -0.90 |          -1.45 |              0.72 |             0.17 |          1.44 |          0.34 |
|   30 |          -1.66 |          -0.94 |          -1.42 |              0.72 |             0.24 |          1.44 |          0.48 |
|------+----------------+----------------+----------------+-------------------+------------------+---------------+---------------|
|      | -1.59 +/- 0.02 | -0.93 +/- 0.02 | -1.47 +/- 0.03 |     0.66 +/- 0.03 |    0.12 +/- 0.04 | 1.32 +/- 0.06 | 0.24 +/- 0.08 |
#+TBLFM: $5=$3 - $2;f2::$6=$4 - $2;f2::$7=2 $5;f2::$8=2 $6;f2::@14$2..@14$4=vmeane(@I..@IIII); f2

** Original data tables from Jane



*** vca-11-tab.dat - z-axis
          Thick            Thin

Halpha
No broadening
15        -1.65           -1.11		
20        -1.63           -1.00
25        -1.61           -0.88
30        -1.56           -0.85
Broadening
15        -1.65           -1.65
20        -1.63           -1.56
25        -1.61           -1.42
30        -1.56           -1.30

O35007
No broadening
15        -2.58           -1.32
20        -2.32           -1.13
25        -2.37           -1.07
30        -2.38           -0.98
Broadening
15        -2.58           -2.01
20        -2.32           -1.74
25        -2.37           -1.66
30        -2.38           -1.57

N26584
No broadening
15        -1.41           -0.80
20        -1.61           -0.83
25        -1.42           -0.81
30        -1.58           -0.89
Broadening
15        -1.41           -1.24
20        -1.61           -1.31
25        -1.42           -1.23
30        -1.58           -1.30

S26716
No broadening
15        -1.13           -0.46
20        -1.03           -0.41
25        -0.84           -0.28
30        -0.85           -0.24
Broadening
15        -1.13           -0.85
20        -1.03           -0.84
25        -0.84           -0.65
30        -0.85           -0.58

*** vca-21-tab.dat - y-axis
          Thick            Thin

Halpha
No broadening
15        -1.52           -0.96                    		
20        -1.55           -0.93
25        -1.60           -0.92
30        -1.53           -0.86
Broadening
15        -1.52           -1.61
20        -1.55           -1.48
25        -1.60           -1.38
30        -1.53           -1.33

O35007
No broadening
15        -2.14           -1.07        
20        -2.18           -1.04
25        -2.31           -1.03
30        -2.39           -0.97
Broadening
15        -2.14           -1.85
20        -2.18           -1.64
25        -2.31           -1.59
30        -2.39           -1.56

N26584
No broadening
15        -1.38           -0.70
20        -1.48           -0.84
25        -1.61           -0.89
30        -1.52           -0.86
Broadening
15        -1.38           -1.16
20        -1.48           -1.26
25        -1.61           -1.33
30        -1.52           -1.29

S26716
No broadening
15        -0.96           -0.29
20        -0.82           -0.34
25        -1.19           -0.51
30        -0.92           -0.24
Broadening
15        -0.96           -0.64
20        -0.82           -0.65
25        -1.19           -0.91
30        -0.92           -0.61

*** vca-31-tab.dat - x-axis
          Thick            Thin

Halpha
No broadening
15        -1.66           -0.92                            		
20        -1.49           -0.91
25        -1.62           -0.90
30        -1.66           -0.94
Broadening
15        -1.66           -1.62
20        -1.49           -1.40
25        -1.62           -1.45
30        -1.66           -1.42

O35007
No broadening
15        -2.42           -0.98        
20        -2.26           -1.01
25        -2.34           -0.99
30        -2.43           -1.10
Broadening
15        -2.42           -1.60
20        -2.26           -1.58
25        -2.34           -1.59
30        -2.43           -1.68

N26584
No broadening
15        -1.42           -0.80
20        -1.44           -0.82
25        -1.63           -0.88
30        -1.66           -0.91
Broadening
15        -1.42           -1.25
20        -1.44           -1.25
25        -1.63           -1.34
30        -1.66           -1.39

S26716
No broadening
15        -1.21           -0.57
20        -1.09           -0.44
25        -0.96           -0.29
30        xxx             xxx
Broadening
15        -1.21           -0.93
20        -1.09           -0.80
25        -0.96           -0.75
30        xxx             xxx





