Stuff for the Sac and Jane paper on turbulence diagnostics

* Latex material for discussion
#+BEGIN_SRC latex
  \newcounter{ionstage}
  \newcommand{\ion}[2]{\setcounter{ionstage}{#2}% 
    \ensuremath{\mathrm{#1\,\scriptstyle\Roman{ionstage}}}}
  \newcommand\nii{[\ion{N}{2}]}
  \newcommand\sii{[\ion{S}{2}]}
  \newcommand\oiii{[\ion{O}{3}]}
  \newcommand\ha{\ensuremath{\mathrm{H\alpha}}}
  \newcommand\hii{\ion{H}{1}}
  
  % INTRINSIC POWER SPECTRA OF PHYSICAL QUANTITIES
  Figure~\ref{fig:intrinsic-power-spectra} shows that
  the power spectra of physical quantities are very well approximated
  by power laws over the range from \(k = 4 \to 32\)
  (scales of 1~pc to 0.125~pc).
  In particular, the ionized gas velocity shows
  a power law slope of \(\mu = -3.2 \pm 0.1\)
  once the turbulence is fully developed. 
  This is significantly shallower than the Kolmogorov (\(\mu = -3.667\))
  or Burgers (\(\mu = -4\)) value,
  indicating more velocity structure at small scales than would be seen
  in a simple turbulent cascade of energy injected at the largest scale.
  One reason for this may be that energy is injected over a variety of scales.
  As a consequence,
  the turbulent velocity dispersion is relatively insensitive to scale,
  varying as \(\sigma \sim L^{0.5 (-3 - \mu)} \sim L^{0.01}\). 
  
  The density has a very similar slope to the velocity: \(n = -3.2 \pm 0.1\),
  but of greater relevance
  are the slopes of the emissivities of the different emission lines,
  which are \(n = -3.4 \pm 0.1\) for \oiii{}, 
  \(n = -2.9 \pm 0.1\) for \ha,
  \(n = -2.7 \pm 0.1\) for \nii, and
  \(n = -2.6 \pm 0.1\) for \sii.
  These span the critical value of \(n = -3\)
  that divides ``steep'' from ``shallow'' power spectra.
  \oiii{} has a steep slope,
  indicating that large-scale fluctuations dominate,
  while \nii{} and \sii{} have shallow slopes,
  indicating that small-scale fluctuations dominate. 
  The \ha{} slope is very close to the critical value,
  indicating roughly equal contributions from fluctuations on all size-scales.
  
  % DETERMINING \mu AND n FROM OBSERVATIONAL DIAGNOSTICS
  It is interesting to study the question of whether
  the known power law indices of the velocity and emissivity power spectra in our simulations
  can in practice be recovered from observational diagnostics.  
  If this is not the case for a given diagnostic,
  then it would call into question its utility for studying real \hii{} regions.
  In particular, we will concentrate on two commonly used diagnostics:
  the second-order structure function of the line velocity centroids,
  and the power spectra of the surface brightness in isovelocity channel maps
  (Velocity Channel Analysis). 
  
  % STRUCTURE FUNCTION
  The structure function of the velocity centroids is an observationally attractive diagnostic
  because it is relatively immune to the effects of thermal broadening 
  and poor spectral resolution,
  so long as sufficiently high signal-to-noise spectra are used. 
  However, it has the disadvantage that relating the observed slope 
  to the 3-dimensional velocity statistics depends on the geometry
  of the emitting region, see \S~\ref{sec:projection-smoothing}. 
  For transverse separations larger than
  the characteristic line-of-sight depth of the emitting gas,
  the two-dimensional gradient should be equal to the three-dimensional one:
  \[
  m_{\mathrm{2D}} = m_{\mathrm{3D}} = -3 - \mu,
  \]
  whereas at smaller separations than this, 
  projection smoothing, as described above, means that 
  the two-dimensional gradient is steeper:
  \[
  m_{\mathrm{2D}} = 1 + m_{\mathrm{3D}} = -2 - \mu.
  \]
  Based on our simulation's velocity power spectrum index of \(\mu \approx -3.2\), 
  the structure function slope should be \(m_{\mathrm{2D}} = 0.2\) in the large-scale limit
  and \(m_{\mathrm{2D}} = 1.2\) in the small-scale limit. 
  
  In fact, all of the measured slopes lie between these two limits,
  with a systematically increasing value from low to high-ionization lines:
  \(m_{\mathrm{2D}}(\sii) = 0.45 \pm 0.01\), 
  \(m_{\mathrm{2D}}(\nii) = 0.55 \pm 0.02\), 
  \(m_{\mathrm{2D}}(\ha) = 0.60 \pm 0.03\), 
  \(m_{\mathrm{2D}}(\oiii) = 0.75 \pm 0.03\). 
  This is qualitatively consistent with expectations
  because the emission from lower-ionization lines is confined to 
  thin layers near the ionization front, whereas higher ionization emission
  is more distributed over the volume
  and therefore subject to greater projection smoothing.
  
  If the line-of-sight depth were constant over the face of the \hii{} region,
  then the structure function would show a break at that scale,
  but in reality the depth varies from point to point, 
  so the break will be blurred out.
  Instead, the structure function is expected to show negative curvature,
  with the gradient gradually decreasing 
  as one passes from smaller to larger scales. 
  A small such effect is seen in the structure functions 
  derived from our simulations (Fig.~\ref{fig:strucfunc-x} to \ref{fig:strucfunc-z}):
  the fit to a power law is generally not so good as in the case of the power spectra,
  with negative residuals at both ends of the fitted range,
  indicative of a negative curvature.  
  That the observed effect is so small is probably due to the fact that
  the distribution of line-of-sight depths strongly overlaps with 
  the limited dynamic range in separations available from our simulations,
  bounded at small scales by numerical dissipation,
  and at large scales by the size of the ionized region.
  
  It is disappointing that none of the measured slopes
  reach either of the limiting cases discussed above.
  All that can be deduced from the structure function is that 
  \(1 + m_{\mathrm{3D}} > m_{\mathrm{2D}}(\oiii)\) 
  and \(m_{\mathrm{3D}} < m_{\mathrm{2D}}(\sii)\), which implies \(\mu = -2.75 \to -3.45\).
  Although this is a rather wide range of allowed velocity power spectrum slopes,
  it does serve to rule out the Kolmogorov value of \(\mu = -3.667\). 
  
  A further proviso to the use of the structure function is that
  systematic anisotropic flows can affect the measured slopes
  when the viewing angle is along the direction of the flow.
  Such an effect is seen at later times for our simulation
  when viewed along the \(x\)-axis (Fig.~\ref{fig:strucfunc-x}). 
  In this case, the structure function tends to steepen
  at the large-scale end of our fitting range,
  producing a positive curvature, 
  which is opposite to the more typical case of negative curvature discussed above.
  Such cases may also be identified by the presence of a significant skew
  in the PDF of the line-of-sight velocity (see Fig.~\ref{fig:velocity-PDFs}).
  
  Note that the additional complication identified by \citet{Brunt:2004a}, 
  whereby correlations between density and velocity fluctuations affect the 
  translation between \(m_{\mathrm{2D}}\) and \(\mu\), 
  is likely of minor importance in our case.  
  \citet{Esquivel:2007b} show that this is most important
  for high Mach number turbulence, where \(\delta\rho/\langle \rho \rangle > 1\),
  whereas the transonic turbulence inside our simulated \hii{} regions
  produces more modest density contrasts. 
  
  % VCA
  The velocity channel analysis consists of calculating the
  two-dimensional power spectrum of the brightness distribution
  in isovelocity channels of varying thickness.  
  We consider two cases: thick slices,
  which are wide enough (\(\sim 100~\mathrm{km\ s^{-1}}\))
  to include all the emission in the line,
  and thin slices, with width \(5~\mathrm{km\ s^{-1}}\). 
  Because the velocity spectrum in our simulations is rather shallow (see above),
  the line-of-sight turbulent velocity dispersion \(\delta v\)
  exceeds the width of these thin slices
  over the full range of length scales that we can usefully study,
  from \(0.1\)~pc (\(\delta v \approx 8~\mathrm{km\ s^-1}\))
  to \(1\)~pc (\(\delta v \approx 10~\mathrm{km\ s^-1}\)). 
  
  To use thinner slices would not be useful for a variety of reasons.
  First, \(5~\mathrm{km\ s^{-1}}\) corresponds to the highest resolution 
  that can be achieved with optical spectrographs
  that are optimised for studying extended sources. 
  Second, thinner slices are increasingly subject to ``shot noise'' 
  due to the finite resolution of the numerical simulations,
  which produces spurious small-scale power, as discussed by 
  \citet{Esquivel:2003a} and \citet{Miville-Deschenes:2003a}.
  Third, thermal broadening would smoothe out any structure on 
  scales \(< 5~\mathrm{km\ s^{-1}}\) for all but the heaviest ions.
  
  
#+END_SRC

* Conclusions
** DONE Intrinsic power spectra of physical quantities
CLOSED: [2013-12-14 Sat 17:40]
+ [X] We have good power laws over a reasonable range
+ [X] Ionized gas velocity has slope \mu = -3.2 \pm 0.1 once the turbulence is fully developed
  + This rather shallow compared with Kolmogorov (\mu = -3.667) or Burgers (\mu = -4.0), implying relatively more velocity structure at smaller scales than is seen in an inertial cascade
  + One reason for this may be the injection of energy at all scales
  + The associated autocorrelation slope of u^2 (or second-order structure function slope) is m = -3 - \mu = 0.2 \pm 0.1, where \delta{}u \sim L^{m/2}
  + So u \sim L^{0.1 \pm 0.05}, which is remarkably shallow.  It means that with \sigma \approx 10 km/s on scale of 1 pc, we will still have \sigma = 8 km/s on scale of 0.1 pc
+ [X] Density has slope n = -3.2, same as velocity, but more relevant are emissivity slopes: n = -2.9 \pm 0.1 for H\alpha and n = -3.4 \pm 0.1 for [O III]
** DONE We want to see if we can diagnose the intrinsic power spectrum from observables
CLOSED: [2013-12-13 Fri 17:55]
+ In particular the power law index of the ionized gas velocity power spectrum, which is -3.2 \pm 0.1 in our simulations
+ Can it be deduced from the /Structure Function/ or the /Velocity Channel Analysis/?
*** DONE Structure function
CLOSED: [2013-12-14 Sat 16:28]
+ [X] has big advantage that it is relatively immune to effects of thermal broadening and poor instrumental resolution, so can be used for H\alpha
+ big disadvantage that it has the uncertainty of projection smoothing
  + [X] smoothing should apply at scales smaller than the characteristic line-of-sight depth of the emitting gas
  + [X] would give a break of magnitude \delta{}m = 1 in the spectrum (steeper at smaller scales, where the smoothing operates)
  + [X] except that the line-of-sight depth has a distribution, rather than a fixed value, since it varies from point to point, so that instead of a break, we should see a negative curvature to the structure function over the fitted range
  + [X] Just such curvature is seen (mostly)
  + [X] In addition, we see a clear progression from [S II] \to [N II] \to H\alpha \to [O III]
    + m_{2D}([S II]) = 0.45 \pm 0.01
    + m_{2D}([N II]) = 0.55 \pm 0.02
    + m_{2D}(H\alpha) = 0.60 \pm 0.03
    + m_{2D}([O III]) = 0.75 \pm 0.03
  + [X] Based on the simulation's velocity power spectrum index of \mu \approx -3.2, this should have a value between:
    + m_{2D} = 0.2 (no smoothing), and
    + m_{2D} = 1.2 (full smoothing)
  + [X] The results are obviously consistent with this, and seem to follow a consistent trend with less smoothing (shallower spectrum) where the emission is more sheet-like ([S II]), progressing to more smoothing where the emission is more diffuse ([O III])
  + [X] But nothing is clearly in any particular limit, so it is hard to infer \mu from the observations
    + The limits are 1 + m_3D > 0.75 \pm 0.03 and m_3D < 0.45 \pm 0.01
    + => m_3D = -0.25 \to 0.45 => \mu = 2.75 \to 3.45 = 3.1 \pm 0.35
    + Although this does rule out Kolmogorov: \mu = 3.667
  + [X] PLUS added complication of the Brunt & Mac Low (2004) effect, where density (emissivity) fluctuations correlated with the velocity fluctuations can effect the velocity centroid distributions and partially or fully cancel out the projection smoothing effect
    + For a compressible flow, the structure function of the velocity centroids is not solely a function of the POS variation of the LOS velocity, as it is in the incompressible case.  Instead, there will be a contribution from the interaction of the LOS variations of LOS velocity with LOS+POS variations of emissivity
    + But Lazarian (2007) say that this depends on \delta\rho
  + [X] PLUS AGAIN it is affected by champagne flows along line of sight, which steepen the structure function without any concommitant change in \mu
    + This happens mainly at the larger separations in the fitting range, which gives it a positive curvature, allowing it to be potentially spotted.  Another telltale sign is a shoulder on the velocity PDF
*** TODO VCA
+ [X] We use 5 km/s slices as the thin limit
  + This is the highest resolution that can regularly be achieved with current echelle spectrographs
  + Also, thermal broadening means that most lines would not benefit from going to higher resolution
  + And smaller slices also run into problems with discretization noise in the simulations that produces spurious small-scale power, as discussed by Esquivel
+ [ ] The thick slices should have an index \gamma_{thick} equal to the power law index n of the 3D power spectrum of the line emissivity in all cases (/but are we really sure of this/):
  + [O III]: \gamma_{thick} = -3.33 \pm 0.03, n = -3.4 \pm 0.1 /YES/
  + H\alpha:  \gamma_{thick} = -2.59 \pm 0.02, n = -2.95 \pm 0.15 /PCA thick slope is too shallow!/
  + [N II]: \gamma_{thick} = -2.51 \pm 0.03, n = -2.7
  + [S II]: \gamma_{thick} = -1.99 \pm 0.03, n = -2.6
+ [ ] The thin slices, with width < \delta{}v(k), should have a shallower slope \gamma_{thin}, which depends on the velocity fluctuations \mu, or equivalently m = 3 - \mu
+ [ ] There are two cases:
  + steep emissivity, n < -3, appropriate to [O III]: \gamma_{thin} = -3 + m/2
    + [O III]: \gamma_{thin} = -2.84 \pm 0.11 (x-axis), -3 + m/2 = -2.9 /YES/
  + shallow emissivity, n > -3, appropriate to the other lines:  \gamma_{thin} - \gamma_{thick} = m/2
    + H\alpha: \gamma_{thin} - \gamma_{thick} = 0.08 +/- 0.04
    + [N II]: \gamma_{thin} - \gamma_{thick} = 0.18 \pm 0.04
    + [S II]: \gamma_{thin} - \gamma_{thick} = 0.18 \pm 0.04
    + Should all be compared with m/2 = 0.1 \pm 0.05

 
* Why projection smoothing may not happen
- Projection smoothing makes the 2D structure (or autocorrelation) function steeper than the 3D one by 1.
- It will only happen for transverse scales smaller than the line-of-sight depth of the emitting layer
  + If there were a unique scale for the line-of-sight depth of the emitting layer, then there should be a break in the structure function at that scale
  + But since there will be a distribution of LOS depths, we will instead see a curvature of the structure function
    + We could measure the LOS depths - maybe for the observational paper
    + For instance z = \int \eta dz / \eta_max - although this would be a lower limit on the real effective depth
- But there is also the Brunt & Mac Low (2004) effect, where density fluctuations have an effect on the velocity centroids that can fully or partially cancel out the projection smoothing
*** Shapes of the structure functions
+ For all but the "champagne flow" case, the structure functions have negative curvature over the "power law" range
  + That is \partial{}^{2}S_2/\partial{}l^2 < 0
  + This might be hint of passing from thick to thin regime, see above
+ For looking down the z-axis, where we see a champagne flow, the structure functions have a curvature in the opposite direction
  

* Slopes of VCA power spectra

** Checking what bin width we should use
+ [X] Jane is going to save the velocity channels for me
+ I suspect that the flat slopes for the thinnest channels are due to noise
+ Turns out that channels of 5 km/s are fine
*** Velocity widths
All the n=128 PPV cubes have 1.2667 km/s channels

|   n |    dV |
|-----+-------|
| 128 |   1.3 |
|  64 |   2.5 |
|  32 |   5.1 |
|  16 |  10.1 |
|   8 |  20.3 |
|   4 |  40.5 |
|   2 |  81.1 |
|   1 | 162.1 |
#+TBLFM: $2=1.2667 (128/$1) ; f1
*** Make figure of velocity slices
#+BEGIN_SRC python :results file
from astropy.io import fits

return figfile
#+END_SRC
*** Halve resolution of PPV cube
#+BEGIN_SRC python :results output
  import numpy as np
  from astropy.io import fits
  
  def double_down(ppv):
      nv, ny, nx = ppv.shape
      return np.reshape(ppv, (nv/2, 2, ny, nx)).sum(axis=1)

  PREFIX = "04052012_4_0030-cube"
  def all_the_way(suffix):
      hdu, = fits.open("bigdata/{}-{}.fits".format(PREFIX, suffix))
      while hdu.data.shape[0] > 1:
          hdu.data = double_down(hdu.data)
          hdu.writeto("bigdata/{}-{:03d}.fits".format(suffix, hdu.data.shape[0]), clobber=True)

  cubes = ["y-Halpha", "n-Halpha", "y-O35007", "n-O35007", 
           "y-Halpha", "n-Halpha", "y-O35007", "n-O35007", ]
  for cube in cubes:
      all_the_way(cube)
#+END_SRC

#+RESULTS:
#+begin_example
WARNING: Overwriting existing file 'bigdata/y-Halpha-064.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/y-Halpha-032.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/y-Halpha-016.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/y-Halpha-008.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/y-Halpha-004.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/y-Halpha-002.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/y-Halpha-001.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/n-Halpha-064.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/n-Halpha-032.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/n-Halpha-016.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/n-Halpha-008.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/n-Halpha-004.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/n-Halpha-002.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/n-Halpha-001.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/y-O35007-064.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/y-O35007-032.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/y-O35007-016.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/y-O35007-008.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/y-O35007-004.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/y-O35007-002.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/y-O35007-001.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/n-O35007-064.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/n-O35007-032.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/n-O35007-016.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/n-O35007-008.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/n-O35007-004.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/n-O35007-002.fits'. [astropy.io.fits.hdu.hdulist]
WARNING: Overwriting existing file 'bigdata/n-O35007-001.fits'. [astropy.io.fits.hdu.hdulist]
#+end_example

** Problems with the thick velocity slices

+ 
** From Esquivel, Lazarian, Pogosyan, & Cho (2003)
+ n is 3D density spectral index (negative)
  + We have \kappa = n + 2, but we also use m for same thing
  + In our case, it is the emissivity rather than density that is relevant
  + Simulations:
    + \kappa(d_i) \simeq -1.2
    + \kappa(d_i^2) = \kappa(H\alpha) \simeq -1.1 \to -0.8 \to -0.9
    + \kappa([O III]) \simeq -1.5 \to -1.3
  + The shallow/steep boundary is at -1 in our units, so we are hovering around the boundary, with [O III] steep and H\alpha shallow
+ \mu is 3D velocity spectral index (negative)
  + Simulations have \kappa(v_i) \simeq -1.3 \to -1.1 \to -1.2 
+ \gamma is spectral index in velocity slices (negative)
+ m is structure function index of the velocity (positive)
  + We use 2\gamma for the same quantity, but then use m in the table
    + This comes from \Delta{}v_rms \sim L^\gamma
    + Kolmogorov,Burger predict \gamma = 1/3,1/2 => m_{3D} = 2/3,1
  + But this is 3D, not 2D.  Does it make a difference?
    + *Maybe*
      + Projection smoothing gives m_{2D} = m_{3D} + 1
      + But we can have m_{2D} = m_{3D} in certain cases:
        1. If line-of-sight depth of emitting region is smaller than separation scale
           - this should certainly be the case for the [N II] and [S II] lines
        2. In driven turbulence, correlations \Delta\rho-\Delta{}v can undo the projection smoothing (Brunt & Mac Low 2004)
      + In general we can put  m_{2D} = m_{3D} + \delta_{smooth}, where \delta_{smooth} = [0 \dots 1] 
    + Simulation measurements have
      + m_{2D}([S II]) = 0.45 \pm 0.01
      + m_{2D}([N II]) = 0.55 \pm 0.02
      + m_{2D}(H\alpha) = 0.60 \pm 0.03
      + m_{2D}([O III]) = 0.75 \pm 0.03
        + Except for xy plane where it reaches 1.0
    + *If we believe projection smoothing* => m_{3D} \approx -0.45 (H\alpha) or -0.3 ([O III])
      + If we don't, then it could be anywhere in the range m_{3D} \approx -0.45 \rightarrow 0.55
    + Prediction from velocity power spectrum is
      + m = -3 - \mu = -1 - \kappa(v_i) = 0.3 \to 0.1 \to 0.2
    + Average m = 0.2 \pm 0.1, so we can see that \delta_{smooth} varies from 0.25 for [S II] up to 0.55 for [O III]
      + It increases as the emitting region geometry transitions from sheet-like to diffuse
      + It is not zero even for [S II], presumably because there is /some/ diffuse emission, and/or we sometimes

\alpha\beta\gamma\delta\epsilon\zeta\eta\theta\iota\kappa\lambda\mu\nu\omicron\pi\varpi\rho\sigma\tau\upsilon\xi\chi\omega \Alpha\Beta\Gamma\Delta\Epsilon\Zeta\Eta\Theta\Iota\Kappa\Lambda\Mu\Nu\Omicron\Pi\Rho\Sigma\sum\Tau\Upsilon\Xi\Chi\Omega


*** Table of structure function indices
| Time        | 150,000 |      |      | 200,000 |      |      | 250,000 |      |      | 300,000 |      |      |               |
| Plane       |     x−y |  x−z |  y−z |     x−y |  x−z |  y−z |     x−y |  x−z |  y−z |     x−y |  x−z |  y−z | AVERAGE       |
|-------------+---------+------+------+---------+------+------+---------+------+------+---------+------+------+---------------|
| Hα          |    0.51 | 0.60 | 0.67 |    0.61 | 0.51 | 0.60 |    0.71 | 0.53 | 0.51 |    0.79 | 0.58 | 0.61 | 0.60 +/- 0.03 |
| [OIII]λ5007 |    0.69 | 0.77 | 0.87 |    0.68 | 0.78 | 0.70 |    0.83 | 0.73 | 0.59 |    1.02 | 0.63 | 0.74 | 0.75 +/- 0.03 |
| [NII]λ6584  |    0.46 | 0.54 | 0.58 |    0.54 | 0.44 | 0.56 |    0.60 | 0.48 | 0.55 |    0.66 | 0.63 | 0.53 | 0.55 +/- 0.02 |
| [SII]λ6716  |    0.41 | 0.44 | 0.50 |    0.44 | 0.37 | 0.47 |    0.45 | 0.43 | 0.48 |    0.43 | 0.47 | 0.48 | 0.45 +/- 0.01 |
#+TBLFM: $14=vmeane($2..$13); f2



*** Relation between velocity energy spectrum \mu and structure function m
+ In three dimensions: \mu = -3 - m
+ From simulations: m = -0.45 \rightarrow 0.55 => \mu = -2.55 \rightarrow -3.55
+ Whereas really the simulations have \mu = -3.2 \pm 0.1

*** Relation between m and VCA slope \gamma
**** Shallow density spectrum:
+ \gamma_{thin} = n + m/2
+ \gamma_{thick} = n
**** Steep density spectrum:
+ \gamma_{thin} = -3 + m/2
+ \gamma_{thick} = -3 - m/2
+ \gamma_{THICK} = n  (THICK means basically the whole line)
**** Our simulations
+ We have \mu = -3.2 \pm 0.1, m = 0.2 \pm 0.1, n([O III]) = -3.4 \pm 0.1, n(H\alpha) = -2.95 \pm 0.15
***** Predicted [O III] steep
+ \gamma_{thin} = -2.9 \pm 0.1 - observed: -2.84 \pm 0.11 (x-axis)
+ \gamma_{thick} = -3.2 \pm 0.1 - NOT OBSERVED
  + But this is just the thinnest case with thermal broadening; we don't actually know it corresponds to the "thick" case
+ \gamma_{THICK}_{} = -3.4 \pm 0.1 - observed: -3.38 \pm 0.04
+ So this works well
***** Predicted H\alpha shallow
+ \gamma_{thin} = -2.85 \pm 0.15 - observed -2.5 
+ \gamma_{thick} = -2.95 \pm 0.15 - observed -2.59 \pm 0.02 
+ So the difference between them is 0.1, which is what is expected
+ But the absolute value of the thick index is too shallow
**** Deduction of m from VCA slopes

***** Shallow, applied to H\alpha
+ => m = 2 (\gamma_{thin} - \gamma_{thick})
+ This gives 0.66 \pm 0.03 with no broadening, which is too steep
+ With broadening it gives 0.24 \pm 0.08, which is the right answer!
  + But it must be a coincidence

***** Steep, applied to [O III]
****** Just thin
+ m = 2 (3 + \gamma_{thin})
+ From "observed" \gamma_{thin} = -2.06 \pm 0.03 => m = 1.88 +/- 0.06
  + This is far too steep => \mu = -4.9
+ With thermal broadening, the observed \gamma_{thin} = -2.67 \pm 0.04 => m = 0.66 +/- 0.08
  + Still too large (\mu = -3.7), but more reasonable
****** Old useless stuff
******* Thin \to medium thick
+ => m = (\gamma_{thin} - \gamma_{thick})
******* Medium thick \to very thick
+ AND \gamma_{thick} - \gamma_{THICK} = -3 - n - m/2
+ => m = 2 [-(n + 3) - (\gamma_{thick} - \gamma_{THICK})]
+ OR \gamma_{thin} - \gamma_{THICK} = -3 - n + m/2
+ => m = 2 [ (n + 3) + (\gamma_{thin} - \gamma_{THICK}) ]
******* Application to [O III]
+ For [O III], n = -3.4 \pm 0.1 => n + 3 = -0.4 \pm 0.1
+ => m_thin = 2 [-0.4 \pm 0.1  + (\gamma_{thin} - \gamma_{THICK})]
+ OR m_med = 2 [0.4 \pm 0.1 - (\gamma_{thick} - \gamma_{THICK})]
+ In the table below we take "Diff NB" = (\gamma_{thin} - \gamma_{THICK})
+ We also try assuming "Diff B" = (\gamma_{thick} - \gamma_{THICK}), *although this is less certain*

** Simulation [O III] slopes

| Time |          Thick |        Thin NB |         Thin B |
|------+----------------+----------------+----------------|
|   15 |          -3.47 |          -2.89 |          -3.13 |
|   20 |          -3.29 |          -2.63 |          -2.85 |
|   25 |          -3.40 |          -2.52 |          -2.74 |
|   30 |          -3.37 |          -2.41 |          -2.64 |
|------+----------------+----------------+----------------|
|   15 |          -3.14 |          -2.73 |          -3.01 |
|   20 |          -3.18 |          -2.55 |          -2.76 |
|   25 |          -3.31 |          -2.48 |          -2.69 |
|   30 |          -3.39 |          -2.46 |          -2.68 |
|------+----------------+----------------+----------------|
|   15 |          -3.42 |          -2.51 |          -2.71 |
|   20 |          -3.26 |          -2.51 |          -2.69 |
|   25 |          -3.34 |          -2.45 |          -2.69 |
|   30 |          -3.43 |          -2.58 |          -2.79 |
|------+----------------+----------------+----------------|
|      | -3.33 +/- 0.03 | -2.56 +/- 0.04 | -2.78 +/- 0.04 |
#+TBLFM: @14$2..@14$4=vmeane(@I..@IIII);f2


** Simulation [N II] slopes

| Time |          Thick |        Thin NB |         Thin B |  Thin - Thick |
|------+----------------+----------------+----------------+---------------|
|   15 |          -2.41 |          -2.13 |          -2.28 |          0.13 |
|   20 |          -2.61 |          -2.18 |          -2.36 |          0.25 |
|   25 |          -2.42 |          -2.13 |          -2.28 |          0.14 |
|   30 |          -2.58 |          -2.20 |          -2.35 |          0.23 |
|------+----------------+----------------+----------------+---------------|
|   15 |          -2.38 |          -2.05 |          -2.20 |          0.18 |
|   20 |          -2.48 |          -2.17 |          -2.31 |          0.17 |
|   25 |          -2.61 |          -2.22 |          -2.39 |          0.22 |
|   30 |          -2.52 |          -2.17 |          -2.33 |          0.19 |
|------+----------------+----------------+----------------+---------------|
|   15 |          -2.42 |          -2.16 |          -2.30 |          0.12 |
|   20 |          -2.44 |          -2.14 |          -2.29 |          0.15 |
|   25 |          -2.63 |          -2.22 |          -2.38 |          0.25 |
|   30 |          -2.66 |          -2.28 |          -2.45 |          0.21 |
|------+----------------+----------------+----------------+---------------|
|      | -2.51 +/- 0.03 | -2.17 +/- 0.02 | -2.33 +/- 0.02 | 0.18 +/- 0.04 |
#+TBLFM: $5=$4 - $2;f2::@14$2..@14$4=vmeane(@I..@IIII);f2

** Simulation [S II] slopes
| Time |          Thick |        Thin NB |         Thin B |  Thin - Thick |
|------+----------------+----------------+----------------+---------------|
|   15 |          -2.13 |          -1.76 |          -1.87 |          0.26 |
|   20 |          -2.03 |          -1.82 |          -1.89 |          0.14 |
|   25 |          -1.84 |          -1.69 |          -1.76 |          0.08 |
|   30 |          -1.85 |          -1.59 |          -1.66 |          0.19 |
|------+----------------+----------------+----------------+---------------|
|   15 |          -1.96 |          -1.61 |          -1.69 |          0.27 |
|   20 |          -1.82 |          -1.69 |          -1.74 |          0.08 |
|   25 |          -2.19 |          -1.96 |          -2.02 |          0.17 |
|   30 |          -1.92 |          -1.64 |          -1.71 |          0.21 |
|------+----------------+----------------+----------------+---------------|
|   15 |          -2.11 |          -1.90 |          -1.96 |          0.15 |
|   20 |          -2.04 |          -1.75 |          -1.86 |          0.18 |
|   25 |          -1.97 |          -1.76 |          -1.80 |          0.17 |
|   30 |          -1.96 |          -1.73 |          -1.78 |          0.18 |
|------+----------------+----------------+----------------+---------------|
|      | -1.99 +/- 0.03 | -1.74 +/- 0.03 | -1.81 +/- 0.03 | 0.18 +/- 0.04 |
#+TBLFM: $5=$4 - $2;f2::@14$2..@14$4=vmeane(@I..@IIII);f2



** Simulation H\alpha slopes

| Time |          Thick |        Thin NB |         Thin B |  Thin - Thick |
|------+----------------+----------------+----------------+---------------|
|   15 |          -2.65 |          -2.54 |          -2.67 |         -0.02 |
|   20 |          -2.63 |          -2.41 |          -2.58 |          0.05 |
|   25 |          -2.61 |          -2.31 |          -2.48 |          0.13 |
|   30 |          -2.56 |          -2.23 |          -2.37 |          0.19 |
|------+----------------+----------------+----------------+---------------|
|   15 |          -2.52 |          -2.49 |          -2.63 |         -0.11 |
|   20 |          -2.55 |          -2.35 |          -2.51 |          0.04 |
|   25 |          -2.60 |          -2.29 |          -2.45 |          0.15 |
|   30 |          -2.53 |          -2.23 |          -2.39 |          0.14 |
|------+----------------+----------------+----------------+---------------|
|   15 |          -2.66 |          -2.40 |          -2.64 |          0.02 |
|   20 |          -2.49 |          -2.26 |          -2.42 |          0.07 |
|   25 |          -2.62 |          -2.29 |          -2.50 |          0.12 |
|   30 |          -2.66 |          -2.35 |          -2.48 |          0.18 |
|------+----------------+----------------+----------------+---------------|
|      | -2.59 +/- 0.02 | -2.35 +/- 0.03 | -2.51 +/- 0.03 | 0.08 +/- 0.04 |
#+TBLFM: $5=$4 - $2;f2::@14$2..@14$4=vmeane(@I..@IIII);f2

** Original data tables from Jane                                  :noexport:



*** New vca-11-tab.dat - z-axis
:LOGBOOK:
- Note taken on [2013-12-13 Fri 08:45] \\
  Updated
:END:
          Thick            Thin

Halpha
No broadening
15        -2.65           -2.54		
20        -2.63           -2.41
25        -2.61           -2.31
30        -2.56           -2.23
Broadening
15        -2.65           -2.67
20        -2.63           -2.58
25        -2.61           -2.48
30        -2.56           -2.37

O35007
No broadening
15        -3.58           -2.90
20        -3.32           -2.62
25        -3.37           -2.57
30        -3.38           -2.46
Broadening
15        -3.58           -3.15
20        -3.32           -2.84
25        -3.37           -2.78
30        -3.38           -2.69

N26584
No broadening
15        -2.41           -2.13
20        -2.61           -2.18
25        -2.42           -2.13
30        -2.58           -2.20
Broadening
15        -2.41           -2.28
20        -2.61           -2.36
25        -2.42           -2.28
30        -2.58           -2.35

S26716
No broadening
15        -2.13           -1.76
20        -2.03           -1.82
25        -1.84           -1.69
30        -1.85           -1.59
Broadening
15        -2.13           -1.87
20        -2.03           -1.89
25        -1.84           -1.76
30        -1.85           -1.66

*** New vca-21-tab.dat - y-axis
          Thick            Thin

Halpha
No broadening
15        -2.52           -2.49                    		
20        -2.55           -2.35
25        -2.60           -2.29
30        -2.53           -2.23
Broadening
15        -2.52           -2.63
20        -2.55           -2.51
25        -2.60           -2.45
30        -2.53           -2.39

O35007
No broadening
15        -3.14           -2.73        
20        -3.18           -2.55
25        -3.31           -2.48
30        -3.39           -2.46
Broadening
15        -3.14           -3.01
20        -3.18           -2.76
25        -3.31           -2.69
30        -3.39           -2.68

N26584
No broadening
15        -2.38           -2.05
20        -2.48           -2.17
25        -2.61           -2.22
30        -2.52           -2.17
Broadening
15        -2.38           -2.20
20        -2.48           -2.31
25        -2.61           -2.39
30        -2.52           -2.33

S26716
No broadening
15        -1.96           -1.61
20        -1.82           -1.69
25        -2.19           -1.96
30        -1.92           -1.64
Broadening
15        -1.96           -1.69
20        -1.82           -1.74
25        -2.19           -2.02
30        -1.92           -1.71



*** New vca-31-tab.dat - x-axis
          Thick            Thin

Halpha
No broadening
15        -2.66           -2.40                            		
20        -2.49           -2.26
25        -2.62           -2.29
30        -2.66           -2.35
Broadening
15        -2.66           -2.64
20        -2.49           -2.42
25        -2.62           -2.50
30        -2.66           -2.48

O35007
No broadening
15        -3.42           -2.51        
20        -3.26           -2.51
25        -3.34           -2.45
30        -3.43           -2.58
Broadening
15        -3.42           -2.71
20        -3.26           -2.69
25        -3.34           -2.69
30        -3.43           -2.79

N26584
No broadening
15        -2.42           -2.16
20        -2.44           -2.14
25        -2.63           -2.22
30        -2.66           -2.28
Broadening
15        -2.42           -2.30
20        -2.44           -2.29
25        -2.63           -2.38
30        -2.66           -2.45

S26716
No broadening
15        -2.11           -1.90
20        -2.04           -1.75
25        -1.97           -1.76
30        -1.96           -1.73
Broadening
15        -2.11           -1.96
20        -2.04           -1.86
25        -1.97           -1.80
30        -1.96           -1.78


